// frontend/src/features/knowledge/SuggestedQuestionsFields.tsx
/**
 * 「为每个分段生成推荐问题」的四个设置项（v23；旧 `SuggestedQuestionsFields.vue` 同一份）。
 *
 * 建库弹窗与知识库设置**共用同一份控件**：同一组设置出现两套控件，迟早会出现
 * "建库时能关、设置里关不掉"这种说不清的差别。四个值都由调用方持有
 * （建库时是提交用的草稿，设置里是脏检查用的草稿）。
 *
 * 它跟的是**分段**，不是"空状态的展示"：入库时为每一段让模型出几个问题，
 * 问题并进该段的检索文本，于是用户换个问法也能命中同一段。
 */
import { useEffect } from 'react'

import {
  SUGGESTED_COUNT_DEFAULT,
  SUGGESTED_COUNT_MAX,
  SUGGESTED_COUNT_MIN,
  SUGGESTED_PROMPT_MAX_CHARS,
} from '@/api/knowledgeBases'
import { InfoTip } from '@/features/knowledge/composites'
import { RangeField } from '@/features/knowledge/RangeField'
import { useModelRegistry } from '@/features/knowledge/store'
import { Checkbox } from '@/ui/checkbox'
import { Label } from '@/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/ui/select'
import { Textarea } from '@/ui/textarea'

export interface SuggestedQuestionsValue {
  enabled: boolean
  count: number
  modelPk: string
  prompt: string
}

interface SuggestedQuestionsFieldsProps {
  value: SuggestedQuestionsValue
  onChange: (patch: Partial<SuggestedQuestionsValue>) => void
}

/**
 * 出题时的合并批大小（**与后端 `_CHUNKS_PER_CALL` 一致**）。
 * 只用于把这句代价说明写准确——真正合并发生在后端。
 */
const CHUNKS_PER_CALL_HINT = 8

/** 轨道上的常用值：1 条太薄、2 条兜底、3 条是默认、5 条是上限。 */
const COUNT_MARKS = [
  { value: 2 },
  { value: SUGGESTED_COUNT_DEFAULT, primary: true },
  { value: SUGGESTED_COUNT_MAX },
]

/**
 * 「跟随对话模型」那一项的取值。
 *
 * Radix 的 `<Select.Item>` **不接受空串**（空串被它留作"没有选择"），而这里的值域里
 * `''` 正是"跟随对话模型"。所以界面上用一个哨兵值，进出都换回 `''`——
 * 对外的契约（`SuggestedQuestionsValue.modelPk`）一点没变。
 */
const FOLLOW_CHAT_MODEL = '__follow__'

export function SuggestedQuestionsFields({ value, onChange }: SuggestedQuestionsFieldsProps) {
  const registry = useModelRegistry()

  useEffect(() => {
    // 注册表是缓存 + 后台刷新：拿不到就只显示"跟随对话模型"那一项，
    // 不把"没加载出来"演成一个错误
    void registry.prefetch()
    // 只在挂载时预取一次
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const modelOptions = [
    { value: FOLLOW_CHAT_MODEL, label: '跟随对话模型' },
    ...registry.chatModels.map((model) => ({
      value: model.id,
      label: model.label || model.model_id,
    })),
  ]

  return (
    <div className="kb-suggested">
      <div>
        {/* 14px / 400：这一行是"读得到的选项文字"，label 原语的 12px / 500 是字段标签口径
            （`.kb-switch` 只留布局，字号必须写在调用点——原语内部走 `cn()`，后写者为准） */}
        <Label className="kb-switch text-[length:var(--text-meta-size)] font-normal">
          <Checkbox
            checked={value.enabled}
            aria-label="为每个切块生成推荐问题"
            onCheckedChange={(checked) => onChange({ enabled: checked === true })}
          />
          <span>为每个切块生成推荐问题</span>
        </Label>
        <p className="text-hint">
          入库时为每一段让模型出几个问题，问题会一起进检索索引；只影响<strong>以后上传</strong>
          的文档，已入库的可以在文档列表里选中后点「生成问题」补上。关掉则对话页空状态
          改用内置的静态示例问题。
        </p>
      </div>

      <div className="field">
        <span className="field-label">每个切块生成几条</span>
        <RangeField
          value={value.count}
          onChange={(count) => onChange({ count })}
          min={SUGGESTED_COUNT_MIN}
          max={SUGGESTED_COUNT_MAX}
          marks={COUNT_MARKS}
          ariaLabel="每个切块生成几条问题"
        />
        <p className="text-hint">
          每 {CHUNKS_PER_CALL_HINT} 段合并成一次模型调用；只对之后上传或重新摄入的文档生效。
        </p>
      </div>

      <div className="field">
        <span className="field-label">
          出题用的模型
          <InfoTip text="默认跟随对话页当前选的模型。换一个便宜的小模型可以省 token：出题只需判断这段在讲什么。" />
        </span>
        <Select
          value={value.modelPk || FOLLOW_CHAT_MODEL}
          onValueChange={(modelPk) =>
            onChange({ modelPk: modelPk === FOLLOW_CHAT_MODEL ? '' : modelPk })
          }
        >
          <SelectTrigger aria-label="出题用的模型">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {modelOptions.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="field">
        <span className="field-label">
          自定义出题提示词 <span className="field-optional">可选</span>
        </span>
        <Textarea
          value={value.prompt}
          rows={4}
          maxLength={SUGGESTED_PROMPT_MAX_CHARS}
          placeholder="留空使用内置提示词"
          aria-label="自定义出题提示词"
          onChange={(event) => onChange({ prompt: event.target.value })}
        />
        <p className="text-hint">
          留空即用内置提示词。自定义时它会替换内置那句指令，资料片段照旧附在前面；用
          <code>{'{n}'}</code> 表示条数，并请要求模型<strong>每行输出一个问题</strong>。
        </p>
      </div>
    </div>
  )
}

// frontend/src/components/knowledge/SuggestedQuestionsFields.vue
<script setup lang="ts">
/**
 * 「为每个分段生成推荐问题」的四个设置项（v23），建库弹窗与知识库设置共用同一份。
 *
 * 它跟的是**分段**，不是"空状态的展示"：文档切完块之后，为每一段让模型出几个问题，
 * 问题存进这一段、并进该段的检索文本——用户换一种问法也能命中同一段（提升召回）。
 * 对话页空状态那排胶囊就是从这里取的，**不再单独调模型**。
 *
 * 为什么要抽成组件：这两处**必须完全一致**——同一组设置出现两套控件，
 * 迟早会出现"建库时能关、设置里关不掉"这种说不清的差别。文案与取值范围也只有一份。
 *
 * 四个值都走 `defineModel`，由调用方持有（建库时是提交用的草稿，设置页是脏检查用的草稿）。
 */
import { computed, onMounted } from 'vue'

import {
  SUGGESTED_COUNT_DEFAULT,
  SUGGESTED_COUNT_MAX,
  SUGGESTED_COUNT_MIN,
  SUGGESTED_PROMPT_MAX_CHARS,
} from '@/api/knowledgeBases'
import AppInput from '@/components/ui/AppInput.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import InfoTip from '@/components/ui/InfoTip.vue'
import RangeField from '@/components/ui/RangeField.vue'
import { useModelRegistryStore } from '@/stores/modelRegistry'

const enabled = defineModel<boolean>('enabled', { required: true })
const count = defineModel<number>('count', { required: true })
/** 出题模型；空串 = 跟随对话页当前选的模型。 */
const modelPk = defineModel<string>('modelPk', { required: true })
/** 自定义出题提示词；空串 = 用内置提示词。 */
const prompt = defineModel<string>('prompt', { required: true })

const registryStore = useModelRegistryStore()

onMounted(() => {
  // 注册表是缓存 + 后台刷新：拿不到就只显示"跟随对话模型"那一项，
  // 不把"没加载出来"演成一个错误
  void registryStore.prefetch()
})

const modelOptions = computed(() => [
  { value: '', label: '跟随对话模型' },
  ...registryStore.chatModels.map((model) => ({
    value: model.id,
    label: model.label || model.model_id,
  })),
])

/**
 * 出题时的合并批大小（**与后端 `_CHUNKS_PER_CALL` 一致**）。
 * 只用于把这句代价说明写准确——真正合并发生在后端。
 */
const _CHUNKS_PER_CALL_HINT = 8

/** 轨道上的常用值：1 条太薄、2 条兜底、3 条是默认、5 条是上限。 */
const COUNT_MARKS = [
  { value: 2 },
  { value: SUGGESTED_COUNT_DEFAULT, primary: true },
  { value: SUGGESTED_COUNT_MAX },
]
</script>

<template>
  <div class="suggested">
    <!-- 开关与它那句解释贴在一起（4px），与下一项之间才用大间距 -->
    <div class="suggested-switch">
      <label class="suggested-toggle">
        <input
          type="checkbox"
          :checked="enabled"
          @change="enabled = ($event.target as HTMLInputElement).checked"
        />
        <span>为每个切块生成推荐问题</span>
      </label>
      <!-- 关掉之后到底发生什么、开着要付什么代价，都得写出来——它是一个会花钱的
           入库步骤，用户要在勾之前知道 -->
      <p class="suggested-hint">
        入库时为每一段让模型出几个问题，问题会一起进检索索引，于是用户换个问法也能命中这一段。
        这个开关只影响<strong>以后上传</strong>的文档；已经入库的文档可以在文档列表里选中后点「生成问题」补上。
        关掉则这段能力不参与，对话页空状态改用内置的静态示例问题。
      </p>
    </div>

    <div class="field">
      <span class="field-label">每个切块生成几条</span>
      <RangeField
        v-model="count"
        :min="SUGGESTED_COUNT_MIN"
        :max="SUGGESTED_COUNT_MAX"
        :marks="COUNT_MARKS"
        aria-label="每个切块生成几条问题"
      />
      <!-- 说清"花多少钱、什么时候生效"：这是设置里唯一会持续花钱的开关 -->
      <p class="suggested-hint">
        每 {{ _CHUNKS_PER_CALL_HINT }} 段合并成一次模型调用；只对之后上传或重新摄入的文档生效。
      </p>
    </div>

    <div class="field">
      <span class="field-label">
        出题用的模型
        <InfoTip
          text="默认跟随对话页当前选的模型。换一个便宜的小模型可以省 token：出题只需判断这段在讲什么。"
        />
      </span>
      <AppSelect v-model="modelPk" :options="modelOptions" aria-label="出题用的模型" />
    </div>

    <div class="field">
      <span class="field-label">
        自定义出题提示词
        <span class="field-optional">可选</span>
      </span>
      <AppInput
        v-model="prompt"
        multiline
        :rows="4"
        :maxlength="SUGGESTED_PROMPT_MAX_CHARS"
        placeholder="留空使用内置提示词"
        aria-label="自定义出题提示词"
      />
      <p class="suggested-hint">
        留空即用内置提示词。自定义时它会替换内置那句指令，资料片段照旧附在前面； 用
        <code>{n}</code> 表示条数，并请要求模型<strong>每行输出一个问题</strong>。
      </p>
    </div>
  </div>
</template>

<style scoped>
.suggested {
  display: flex;
  flex-direction: column;
  gap: var(--space-5);
}

/* 开关 + 它的解释是一组：贴紧（4px），别用上面那个"项与项之间"的间距 */
.suggested-switch {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}

/* 开关用原生复选框（与设置页的布尔项同一手法）：文本域里的 "false" 是非空字符串，
   一不小心就写成了"开启"，复选框是唯一不会说反的控件 */
.suggested-toggle {
  display: flex;
  gap: var(--space-2);
  align-items: center;
  font-size: var(--text-meta-size);
  color: var(--text-secondary);
  cursor: pointer;
}

.suggested-toggle input {
  width: 14px;
  height: 14px;
  accent-color: var(--accent);
  cursor: pointer;
}

/* 说明句一律 margin: 0：它跟在控件下面，间距由父级的 gap 给。
   （早先给了一个负外边距想把"开关那句"拉近，结果连输入框下面那句一起拉了，
   文字会压在 textarea 的下边框上。） */
.suggested-hint {
  margin: 0;
  font-size: var(--text-micro-size);
  line-height: 1.7;
  color: var(--text-tertiary);
}

.suggested-hint code {
  padding: 0 3px;
  font-size: 0.95em;
  background: var(--bg-subtle);
  border-radius: var(--radius-control);
}
</style>
