// frontend/src/components/notes/NoteEditor.vue
<script setup lang="ts">
/**
 * 笔记编辑器：**工具栏 + 标题/标签 + 文档画布**（Tiptap，headless）。
 *
 * 为什么是 Tiptap：它是 headless 的，菜单全部自己画，能直接套现有设计令牌，
 * 不会像 Cherry/Vditor 那样自带一套皮肤跟控制台打架（见《笔记功能调研》§2.1）。
 * `content_md` 是唯一事实源——进出这一层的都是 Markdown 字符串，编辑器 JSON 不落库。
 *
 * **画布 `NoteCanvas` 是单实例**：切换笔记靠"原地换文档 + 清撤销栈"（见画布注释），
 * 连文档 DOM 都不重建——只换内容，工具栏/标题/动作/滚动容器全程留在原地。
 *
 * 版式对齐 ima 笔记：工具栏在顶部、标题在文档里、正文走居中窄栏。
 */
import type { Editor } from '@tiptap/core'
import { nextTick, ref, shallowRef, watch } from 'vue'

import { uploadNoteImage, type NoteAiAction } from '@/api/notes'
import IconAi from '@/components/icons/IconAi.vue'
import IconFormatBold from '@/components/icons/IconFormatBold.vue'
import IconFormatBulletList from '@/components/icons/IconFormatBulletList.vue'
import IconFormatCode from '@/components/icons/IconFormatCode.vue'
import IconFormatH1 from '@/components/icons/IconFormatH1.vue'
import IconFormatH2 from '@/components/icons/IconFormatH2.vue'
import IconFormatItalic from '@/components/icons/IconFormatItalic.vue'
import IconFormatLink from '@/components/icons/IconFormatLink.vue'
import IconFormatOrderedList from '@/components/icons/IconFormatOrderedList.vue'
import IconFormatParagraph from '@/components/icons/IconFormatParagraph.vue'
import IconFormatQuote from '@/components/icons/IconFormatQuote.vue'
import IconFormatStrike from '@/components/icons/IconFormatStrike.vue'
import IconFormatTaskList from '@/components/icons/IconFormatTaskList.vue'
import IconFormatUnderline from '@/components/icons/IconFormatUnderline.vue'
import IconImage from '@/components/icons/IconImage.vue'
import IconRedo from '@/components/icons/IconRedo.vue'
import IconUndo from '@/components/icons/IconUndo.vue'
import NoteCanvas from '@/components/notes/NoteCanvas.vue'
import RowMenu from '@/components/ui/RowMenu.vue'

/** 画布实例的公开面：页面在 hover 预取命中后调它预热文档解析。 */
const canvasRef = ref<InstanceType<typeof NoteCanvas> | null>(null)

const props = withDefaults(
  defineProps<{
    modelValue: string
    editable?: boolean
    noteId?: string
    aiBusy?: boolean
    /** 正在等这条笔记的正文（缓存未命中）：给内容一层"正在换"的过渡，别硬切。 */
    loading?: boolean
  }>(),
  { editable: true, noteId: undefined, aiBusy: false, loading: false },
)
const emit = defineEmits<{
  'update:modelValue': [value: string]
  /** 交给页面去弹提示：编辑器不做全局通知。 */
  notify: [payload: { type: 'error' | 'success'; message: string }]
  /** 请求对本篇做一次 AI 处理；由页面负责保存、调用、写回。 */
  ai: [action: NoteAiAction]
}>()

/** 画布交回来的实例；换笔记时会被替换成新的那个。 */
const instance = shallowRef<Editor | null>(null)

function onReady(editor: Editor | null): void {
  instance.value = editor
  refreshActive()
}

function onCanvasChange(): void {
  refreshActive()
}

/**
 * 各按钮的激活/可用态。
 *
 * Tiptap 实例不在 Vue 的响应式图里，不能直接 `computed(isActive)`——
 * 改成"画布每次交易后通知一次"的普通 ref。
 */
const active = ref({
  paragraph: true,
  h1: false,
  h2: false,
  bold: false,
  italic: false,
  underline: false,
  strike: false,
  bullet: false,
  ordered: false,
  task: false,
  quote: false,
  code: false,
  link: false,
  canUndo: false,
  canRedo: false,
})

function refreshActive(): void {
  const current = instance.value
  if (!current) return
  active.value = {
    paragraph: current.isActive('paragraph'),
    h1: current.isActive('heading', { level: 1 }),
    h2: current.isActive('heading', { level: 2 }),
    bold: current.isActive('bold'),
    italic: current.isActive('italic'),
    underline: current.isActive('underline'),
    strike: current.isActive('strike'),
    bullet: current.isActive('bulletList'),
    ordered: current.isActive('orderedList'),
    task: current.isActive('taskList'),
    quote: current.isActive('blockquote'),
    code: current.isActive('codeBlock'),
    link: current.isActive('link'),
    canUndo: current.can().undo(),
    canRedo: current.can().redo(),
  }
}

function run(action: (editor: Editor) => void): void {
  const current = instance.value
  if (!current) return
  action(current)
}

function toggleLink(): void {
  const current = instance.value
  if (!current) return
  if (current.isActive('link')) {
    current.chain().focus().unsetLink().run()
    return
  }
  const url = window.prompt('链接地址（留空则取消）', 'https://')
  if (!url) return
  current.chain().focus().extendMarkRange('link').setLink({ href: url }).run()
}

const fileInput = ref<HTMLInputElement | null>(null)
const uploading = ref(false)

function pickImage(): void {
  fileInput.value?.click()
}

/** 选图 → 上传到后端 → 以带签名的地址插入。图片标签带不了鉴权头，所以必须签名地址。 */
async function onFileChange(event: Event): Promise<void> {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  input.value = '' // 允许连续选同一张
  const current = instance.value
  if (!file || !current) return
  if (!props.noteId) {
    emit('notify', { type: 'error', message: '笔记还没保存，先等一下再插图' })
    return
  }
  uploading.value = true
  try {
    const image = await uploadNoteImage(props.noteId, file)
    current.chain().focus().setImage({ src: image.url, alt: image.alt }).run()
  } catch (cause) {
    emit('notify', {
      type: 'error',
      message: cause instanceof Error ? cause.message : '图片上传失败',
    })
  } finally {
    uploading.value = false
  }
}

/** 选定 AI 动作后交给页面执行（页面负责先保存，再替换正文）。 */
function chooseAi(action: NoteAiAction, close: () => void): void {
  close()
  if (props.aiBusy) return
  emit('ai', action)
}

watch(
  () => props.editable,
  (value) => instance.value?.setEditable(value),
)

/** 转发给画布：提前把某篇的正文解析成文档（切换时省掉这段主线程开销）。 */
function warm(markdown: string): void {
  canvasRef.value?.warm(markdown)
}

defineExpose({ warm })

/**
 * 每条笔记记一个滚动位置。
 *
 * 单实例换文档之后，滚动位置不再被重建——如果不主动处理，切到新笔记会**继承上一条
 * 的滚动位置**（长笔记切走再回来停在半中间很突兀，切到短笔记还会因高度骤减而乱跳）。
 * 记住每条自己的位置，回来时接着看，这也是笔记类应用的常规手感。
 *
 * 注意真正的滚动容器**不是 `.editor-body`**：正文区高度随内容增长，本身并不滚，
 * 会滚的是外层布局的 `main.content`（高度固定、内容溢出）。所以这里往上找
 * 第一个"样式允许滚且确实滚得动"的祖先，而不是写死某个类名。
 */
const bodyRef = ref<HTMLElement | null>(null)
const scrollByNote = new Map<string, number>()

function scrollParentOf(el: HTMLElement | null): HTMLElement | null {
  let node: HTMLElement | null = el
  while (node) {
    const overflowY = getComputedStyle(node).overflowY
    const scrollable = overflowY === 'auto' || overflowY === 'scroll' || overflowY === 'overlay'
    if (scrollable && node.scrollHeight > node.clientHeight + 1) return node
    node = node.parentElement
  }
  return (document.scrollingElement as HTMLElement | null) ?? null
}

watch(
  () => props.noteId,
  (noteId, previous) => {
    if (previous) {
      const scroller = scrollParentOf(bodyRef.value)
      if (scroller) scrollByNote.set(previous, scroller.scrollTop)
    }
    // 等画布把新正文换完再定位：早一步拿到的是旧文档的高度
    void nextTick(() => {
      const scroller = scrollParentOf(bodyRef.value)
      if (scroller) scroller.scrollTop = (noteId && scrollByNote.get(noteId)) || 0
    })
  },
)
</script>

<template>
  <div class="note-editor">
    <div class="toolbar" role="toolbar" aria-label="排版工具栏">
      <div class="tool-group">
        <button
          type="button"
          class="tool"
          title="撤销"
          :disabled="!active.canUndo"
          @click="run((e) => e.chain().focus().undo().run())"
        >
          <IconUndo :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          title="重做"
          :disabled="!active.canRedo"
          @click="run((e) => e.chain().focus().redo().run())"
        >
          <IconRedo :size="15" />
        </button>
      </div>

      <span class="tool-sep" aria-hidden="true" />

      <div class="tool-group">
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.paragraph }"
          title="正文"
          @click="run((e) => e.chain().focus().setParagraph().run())"
        >
          <IconFormatParagraph :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.h1 }"
          title="一级标题"
          @click="run((e) => e.chain().focus().toggleHeading({ level: 1 }).run())"
        >
          <IconFormatH1 :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.h2 }"
          title="二级标题"
          @click="run((e) => e.chain().focus().toggleHeading({ level: 2 }).run())"
        >
          <IconFormatH2 :size="15" />
        </button>
      </div>

      <span class="tool-sep" aria-hidden="true" />

      <div class="tool-group">
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.bold }"
          title="粗体"
          @click="run((e) => e.chain().focus().toggleBold().run())"
        >
          <IconFormatBold :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.italic }"
          title="斜体"
          @click="run((e) => e.chain().focus().toggleItalic().run())"
        >
          <IconFormatItalic :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.underline }"
          title="下划线"
          @click="run((e) => e.chain().focus().toggleUnderline().run())"
        >
          <IconFormatUnderline :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.strike }"
          title="删除线"
          @click="run((e) => e.chain().focus().toggleStrike().run())"
        >
          <IconFormatStrike :size="15" />
        </button>
      </div>

      <span class="tool-sep" aria-hidden="true" />

      <div class="tool-group">
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.bullet }"
          title="无序列表"
          @click="run((e) => e.chain().focus().toggleBulletList().run())"
        >
          <IconFormatBulletList :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.ordered }"
          title="有序列表"
          @click="run((e) => e.chain().focus().toggleOrderedList().run())"
        >
          <IconFormatOrderedList :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.task }"
          title="待办清单"
          @click="run((e) => e.chain().focus().toggleTaskList().run())"
        >
          <IconFormatTaskList :size="15" />
        </button>
      </div>

      <span class="tool-sep" aria-hidden="true" />

      <div class="tool-group">
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.quote }"
          title="引用"
          @click="run((e) => e.chain().focus().toggleBlockquote().run())"
        >
          <IconFormatQuote :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.code }"
          title="代码块"
          @click="run((e) => e.chain().focus().toggleCodeBlock().run())"
        >
          <IconFormatCode :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :class="{ 'tool-on': active.link }"
          title="链接"
          @click="toggleLink"
        >
          <IconFormatLink :size="15" />
        </button>
        <button
          type="button"
          class="tool"
          :disabled="uploading || !noteId"
          :title="noteId ? '插入图片' : '保存后才能插入图片'"
          @click="pickImage"
        >
          <IconImage :size="15" />
        </button>
      </div>

      <div class="toolbar-right">
        <!-- 保存状态放在最左：它是"这条笔记当前的状态"，比任何动作都更该先被看到 -->
        <slot name="status" />
        <!-- AI 处理：星芒图标 + 三档动作下拉。放在格式工具栏与右侧动作之间——
             它属于"对内容做什么"，不属于"对这条笔记做什么"。 -->
        <RowMenu label="AI 处理">
          <template #trigger>
            <span
              class="ai-trigger"
              :class="{ 'ai-busy': aiBusy }"
              :title="aiBusy ? 'AI 正在处理…' : 'AI 处理'"
            >
              <span v-if="aiBusy" class="ai-spinner" aria-hidden="true" />
              <IconAi v-else :size="15" />
              <span class="ai-trigger-text">{{ aiBusy ? '处理中' : 'AI' }}</span>
            </span>
          </template>
          <template #default="{ close }">
            <button type="button" :disabled="aiBusy" @click="chooseAi('format', close)">
              <span class="ai-item-label">智能排版</span>
              <span class="ai-item-hint">只调分段与标题，不改文字</span>
            </button>
            <button type="button" :disabled="aiBusy" @click="chooseAi('polish', close)">
              <span class="ai-item-label">内容润色</span>
              <span class="ai-item-hint">只改措辞与标点，不动结构</span>
            </button>
            <button type="button" :disabled="aiBusy" @click="chooseAi('both', close)">
              <span class="ai-item-label">排版并润色</span>
              <span class="ai-item-hint">两件事一起做</span>
            </button>
          </template>
        </RowMenu>
        <slot name="actions" />
      </div>

      <input
        ref="fileInput"
        type="file"
        accept="image/png,image/jpeg,image/gif,image/webp,image/bmp"
        class="file-input"
        @change="onFileChange"
      />
    </div>

    <div ref="bodyRef" class="editor-body" :class="{ 'is-loading': loading }">
      <div class="editor-column">
        <slot name="header" />
        <!-- 单实例：切换笔记由画布原地换文档并清撤销栈，这里不上 key、不重建 -->
        <NoteCanvas
          ref="canvasRef"
          :model-value="modelValue"
          :editable="editable"
          :note-id="noteId"
          @update:model-value="emit('update:modelValue', $event)"
          @ready="onReady"
          @change="onCanvasChange"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.note-editor {
  display: flex;
  flex-direction: column;
  min-height: 0;
  height: 100%;
}

.toolbar {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-1);
  padding: var(--space-2) var(--space-3);
  border-bottom: 1px solid var(--border-hairline);
  background: var(--bg-surface);
}

.tool-group {
  display: flex;
  align-items: center;
  gap: 2px;
}

.tool {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  color: var(--text-secondary);
  background: transparent;
  border: none;
  border-radius: var(--radius-control);
  cursor: pointer;
}

.tool:hover:not(:disabled) {
  color: var(--text-primary);
  background: var(--bg-hover);
}

.tool:disabled {
  color: var(--text-tertiary);
  opacity: 0.45;
  cursor: default;
}

.tool-on {
  color: var(--accent-text);
  background: var(--accent-soft);
}

.tool-sep {
  width: 1px;
  height: 16px;
  margin: 0 var(--space-1);
  background: var(--border);
}

.toolbar-right {
  display: flex;
  gap: var(--space-1);
  align-items: center;
  margin-left: auto;
}

/* 工具栏右侧是一个 28px 的按钮排；AI 入口的外框必须同高，否则文字基线会与邻排错开
   （实测：RowMenu 默认触发器是 24px 的方块，带文字的触发器又只有 21px 行高）
   再把 details 本身也变成 flex 项：inline 级盒子按基线对齐，会与按钮差 1px。 */
.toolbar-right :deep(.menu) {
  display: flex;
  align-items: center;
}

.toolbar :deep(.menu-trigger) {
  min-width: 28px;
  height: 28px;
}

.file-input {
  display: none;
}

/* AI 入口：星芒 + 短标签，用强调色与普通格式按钮区分开 */
.ai-trigger {
  display: inline-flex;
  gap: 4px;
  align-items: center;
  height: 21px;
  font-size: var(--text-micro-size);
  font-weight: 600;
  color: var(--accent-text);
}

.ai-busy {
  opacity: 0.8;
}

/* 运行中的进度圈：把星芒换成一个转圈，用户一眼知道"它在跑" */
.ai-spinner {
  width: 13px;
  height: 13px;
  border: 2px solid var(--accent-soft);
  border-top-color: var(--accent);
  border-radius: 999px;
  animation: ai-spin 0.7s linear infinite;
}

@keyframes ai-spin {
  to {
    transform: rotate(360deg);
  }
}

@media (prefers-reduced-motion: reduce) {
  /* 降级成慢转而不是停住：停住就没有"在跑"的信息了 */
  .ai-spinner {
    animation-duration: 1.8s;
  }
}

.ai-item-label {
  display: block;
}

.ai-item-hint {
  display: block;
  margin-top: 2px;
  font-size: var(--text-micro-size);
  color: var(--text-tertiary);
}

.editor-body {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  transition: opacity 160ms ease;
}

/* 正文还在路上（缓存未命中）时把旧内容轻轻压暗：换笔记就有了过渡而不是硬切，
   而这段时间通常刚好够请求回来——回来即恢复，看不出一道闪。
   延迟 120ms 才加这个类（见 NotesView），所以命中缓存的切换完全不会压暗。 */
.editor-body.is-loading {
  opacity: 0.45;
}

@media (prefers-reduced-motion: reduce) {
  .editor-body {
    transition: none;
  }
}

/* 正文收在一条窄栏里居中：满屏宽的行读起来很累，也不像"写作工具" */
.editor-column {
  max-width: 780px;
  margin: 0 auto;
  padding: var(--space-6) var(--space-6) var(--space-16);
}
</style>

// frontend/src/features/notes/NoteEditor.tsx
/**
 * 笔记编辑器：**工具栏 + 标题/标签 + 文档画布**（Tiptap，headless）。
 *
 * 与旧 Vue 版（`frontend/src/components/notes/NoteEditor.vue`）逐条对齐：
 *
 * - 工具栏按钮、分组的顺序与 title 一字不改（撤销/重做｜正文·H1·H2｜粗斜下删｜
 *   无序·有序·待办｜引用·代码·链接·图片｜右侧：上传提示 · 保存状态 · AI · 页面动作）；
 * - 工具栏**吸顶**：吸附对象是正文列的滚动容器（笔记页的 `.notes-pane`），
 *   中间那一级 `.note-editor` 不许有 `overflow: hidden`，`.editor-body` 也刻意不设
 *   overflow——它一旦自己滚起来，列那层就被架空，sticky 从此贴在一个不动的盒子上；
 * - **画布单实例**：换笔记靠"原地换文档 + 清撤销栈"（见 NoteCanvas），
 *   编辑器全程留在原地，工具栏/标题/动作/滚动容器都不重建；
 * - 图片上传的**唯一通道**：工具栏选图与正文粘贴都走 `uploadImageForEditor`；
 * - 每条笔记记一个滚动位置（换文档之后滚动位置不再被重建，不主动处理就会继承上一条的）。
 *
 * 三条与 Vue 版的**有意差异**（都是为了 React 的渲染模型，行为不变）：
 * 1. 工具栏的激活态由"每次交易/换文档递增一个 revision"驱动重渲染（Vue 里靠
 *    `onTransaction` 事件 + 一个普通 ref，React 里重渲染要靠 state）；
 * 2. 滚动位置改成**滚动时随手记**（Vue 版是在 noteId 变化时读一次，读到的已经
 *    是换文档之后的位置，长笔记切短笔记那一瞬间会被钳住）；
 * 3. AI 菜单用 `@/ui/dropdown-menu`（shadcn 原语；旧版是原生 `<details>` 自绘浮层）。
 */
import type { Editor } from '@tiptap/core'
import {
  Bold,
  ChevronDown,
  Code,
  Ellipsis,
  Image as ImageIcon,
  Italic,
  Link as LinkIcon,
  List,
  ListOrdered,
  ListTodo,
  Quote,
  Redo,
  Sparkles,
  Strikethrough,
  Underline as UnderlineIcon,
  Undo,
} from 'lucide-react'
import {
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type ReactNode,
  type Ref,
} from 'react'

import { uploadNoteImage, type NoteAiAction, type NoteImage } from '@/api/notes'
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/ui/dropdown-menu'

import { NoteCanvas, type NoteCanvasHandle } from './NoteCanvas'

export interface NoteEditorHandle {
  /** 转发给画布：提前把某篇的正文解析成文档（切换时省掉这段主线程开销）。 */
  warm(markdown: string): void
}

export interface NoteEditorProps {
  value: string
  editable?: boolean
  noteId?: string
  aiBusy?: boolean
  /** 正在等这条笔记的正文（缓存未命中）：给内容一层"正在换"的过渡，别硬切。 */
  loading?: boolean
  /** 保存状态（页面给，编辑器不做全局通知）。 */
  status?: ReactNode
  /** 对这条笔记的动作（置顶/加入知识库/删除）。 */
  actions?: ReactNode
  /** 文档头（标题输入框、标签行、入库状态）。 */
  header?: ReactNode
  /** 落在根节点上的类名：页面用它挂 `.pane-editor`（撑满正文列但不被压矮）。 */
  className?: string
  onValueChange(value: string): void
  onNotify(payload: { type: 'error' | 'success'; message: string }): void
  /** 请求对本篇做一次 AI 处理；由页面负责保存、调用、写回。 */
  onAi(action: NoteAiAction): void
  ref?: Ref<NoteEditorHandle>
}

/**
 * MIME → 后缀。
 *
 * 剪贴板里的图常常**没有文件名**（截图工具给的是空串或 "blob"），而后端按后缀判
 * 白名单，不补一个必然被"不支持的图片格式"挡回来——这条路径的真实拦路虎就是它。
 */
const SUFFIX_BY_TYPE: Record<string, string> = {
  'image/png': '.png',
  'image/jpeg': '.jpg',
  'image/jpg': '.jpg',
  'image/gif': '.gif',
  'image/webp': '.webp',
  'image/bmp': '.bmp',
}

/**
 * 工具栏各按钮的激活/可用态：读的是**当前**文档与选区。
 *
 * 提到模块级是为了让"块级样式下拉"那张表（`BLOCK_STYLES`）能拿到它的类型——
 * 表里每一项的 `isActive` 都是"这份状态里的某一位"，两处取值口径不会各写一遍。
 * Tiptap 实例不在 React 的响应式图里，所以这里只是**纯函数**，调用方每次渲染现读。
 */
function activeStateOf(current: Editor | null) {
  if (!current || current.isDestroyed) {
    return {
      paragraph: false,
      h1: false,
      h2: false,
      bold: false,
      italic: false,
      underline: false,
      strike: false,
      bullet: false,
      ordered: false,
      task: false,
      quote: false,
      code: false,
      link: false,
      canUndo: false,
      canRedo: false,
    }
  }
  return {
    paragraph: current.isActive('paragraph'),
    h1: current.isActive('heading', { level: 1 }),
    h2: current.isActive('heading', { level: 2 }),
    bold: current.isActive('bold'),
    italic: current.isActive('italic'),
    underline: current.isActive('underline'),
    strike: current.isActive('strike'),
    bullet: current.isActive('bulletList'),
    ordered: current.isActive('orderedList'),
    task: current.isActive('taskList'),
    quote: current.isActive('blockquote'),
    code: current.isActive('codeBlock'),
    link: current.isActive('link'),
    canUndo: current.can().undo(),
    canRedo: current.can().redo(),
  }
}

type ToolbarState = ReturnType<typeof activeStateOf>

/** 「段落样式」下拉的三项：标题是给用户与用例看的同一份口径。 */
const BLOCK_STYLES = [
  {
    title: '正文',
    isActive: (state: ToolbarState) => state.paragraph,
    apply: (editor: Editor) => editor.chain().focus().setParagraph().run(),
  },
  {
    title: '一级标题',
    isActive: (state: ToolbarState) => state.h1,
    apply: (editor: Editor) => editor.chain().focus().toggleHeading({ level: 1 }).run(),
  },
  {
    title: '二级标题',
    isActive: (state: ToolbarState) => state.h2,
    apply: (editor: Editor) => editor.chain().focus().toggleHeading({ level: 2 }).run(),
  },
] as const

/** 触发器上写的是**当前是什么**，不是"可以变成什么"——这正是它此前缺的那点语义。 */
function blockLabel(state: ToolbarState): string {
  return BLOCK_STYLES.find((style) => style.isActive(state))?.title ?? '正文'
}

/** 给没有后缀的图按 MIME 补一个后缀；已经有后缀（哪怕是别的）就不动，让后端去判。 */
function withSuffixFromType(file: File): File {
  const suffix = SUFFIX_BY_TYPE[file.type.toLowerCase()]
  if (!suffix || /\.[a-z0-9]{2,5}$/i.test(file.name)) return file
  const base = file.name.trim() || '粘贴的图片'
  return new File([file], `${base}${suffix}`, { type: file.type })
}

/**
 * 正文滚动容器：往上找第一个"样式允许滚且确实滚得动"的祖先，找不到就退回页面。
 *
 * 不写死类名是刻意的：并排两列时滚的是笔记页的正文列（`.notes-pane`）；
 * 单栏堆叠（<=900px）时那一列把滚动交回了外层 `main.content`。
 * 笔记页那次"两列各自滚"的改造正是靠这一条没被牵动。
 */
function scrollParentOf(el: HTMLElement | null): HTMLElement | null {
  let node: HTMLElement | null = el
  while (node) {
    const overflowY = getComputedStyle(node).overflowY
    const scrollable = overflowY === 'auto' || overflowY === 'scroll' || overflowY === 'overlay'
    if (scrollable && node.scrollHeight > node.clientHeight + 1) return node
    node = node.parentElement
  }
  return (document.scrollingElement as HTMLElement | null) ?? null
}

export function NoteEditor({
  value,
  editable = true,
  noteId,
  aiBusy = false,
  loading = false,
  status,
  actions,
  header,
  className,
  onValueChange,
  onNotify,
  onAi,
  ref,
}: NoteEditorProps) {
  const canvasRef = useRef<NoteCanvasHandle | null>(null)
  const fileInputRef = useRef<HTMLInputElement | null>(null)
  const bodyRef = useRef<HTMLDivElement | null>(null)
  const [uploading, setUploading] = useState(false)

  /**
   * 画布交回来的实例（工具栏的激活态与命令都要用它）。
   *
   * Tiptap 实例不在 React 的响应式图里，不能直接 `useMemo(isActive)`——
   * 改成"画布每次交易后通知一次"的普通 state 计数，下面的 `active` 每渲染现算。
   */
  const instanceRef = useRef<Editor | null>(null)
  const [, forceToolbarRefresh] = useState(0)

  const refresh = useCallback(() => forceToolbarRefresh((count) => count + 1), [])

  const onReady = useCallback(
    (instance: Editor | null) => {
      instanceRef.current = instance
      refresh()
    },
    [refresh],
  )

  /** 各按钮的激活/可用态：每次渲染现读，读到的是**当前**文档与选区。 */
  const active = activeStateOf(instanceRef.current)

  function run(action: (editor: Editor) => void): void {
    const current = instanceRef.current
    if (!current || current.isDestroyed) return
    action(current)
  }

  function toggleLink(): void {
    const current = instanceRef.current
    if (!current || current.isDestroyed) return
    if (current.isActive('link')) {
      current.chain().focus().unsetLink().run()
      return
    }
    const url = window.prompt('链接地址（留空则取消）', 'https://')
    if (!url) return
    current.chain().focus().extendMarkRange('link').setLink({ href: url }).run()
  }

  /**
   * 图片上传的**唯一通道**：工具栏选图与正文粘贴都走它。
   *
   * 失败时返回 null（并弹提示）而**不是**抛异常：调用方据此什么都不插——
   * 半截内容（比如 data URL）留在正文里比"没插上"更糟。
   */
  async function uploadImageForEditor(file: File): Promise<NoteImage | null> {
    if (!noteId) {
      onNotify({ type: 'error', message: '笔记还没保存，先等一下再插图' })
      return null
    }
    setUploading(true)
    try {
      return await uploadNoteImage(noteId, withSuffixFromType(file))
    } catch (cause) {
      onNotify({
        type: 'error',
        message: cause instanceof Error ? cause.message : '图片上传失败',
      })
      return null
    } finally {
      setUploading(false)
    }
  }

  function pickImage(): void {
    fileInputRef.current?.click()
  }

  /** 选图 → 上传到后端 → 以带签名的地址插入。图片标签带不了鉴权头，所以必须签名地址。 */
  async function onFileChange(event: React.ChangeEvent<HTMLInputElement>): Promise<void> {
    const input = event.target
    const file = input.files?.[0]
    input.value = '' // 允许连续选同一张
    if (!file) return
    const image = await uploadImageForEditor(file)
    // 上传期间笔记可能已经切走（画布换的是文档、实例还在），所以落图前重取一次实例
    const current = instanceRef.current
    if (!image || !current || current.isDestroyed) return
    current.chain().focus().setImage({ src: image.url, alt: image.alt }).run()
  }

  /** 选定 AI 动作后交给页面执行（页面负责先保存，再替换正文）。 */
  function chooseAi(action: NoteAiAction): void {
    if (aiBusy) return
    onAi(action)
  }

  useImperativeHandle(
    ref,
    () => ({ warm: (markdown: string) => canvasRef.current?.warm(markdown) }),
    [],
  )

  /**
   * 每条笔记记一个滚动位置。
   *
   * 单实例换文档之后，滚动位置不再被重建——如果不主动处理，切到新笔记会**继承上一条
   * 的滚动位置**（长笔记切走再回来停在半中间很突兀，切到短笔记还会因高度骤减而乱跳）。
   * 记住每条自己的位置，回来时接着看，这也是笔记类应用的常规手感。
   */
  const scrollByNote = useRef(new Map<string, number>())

  useEffect(() => {
    const scroller = scrollParentOf(bodyRef.current)
    if (!scroller) return
    const currentNoteId = noteId
    const onScroll = (): void => {
      if (currentNoteId) scrollByNote.current.set(currentNoteId, scroller.scrollTop)
    }
    scroller.addEventListener('scroll', onScroll, { passive: true })
    return () => {
      onScroll() // 离开这条之前把位置存下来
      scroller.removeEventListener('scroll', onScroll)
    }
  }, [noteId])

  // 画布的换文档 effect 在子组件里先跑，这一条后跑：读到的已经是新文档的高度
  useEffect(() => {
    const scroller = scrollParentOf(bodyRef.current)
    if (scroller) scroller.scrollTop = (noteId && scrollByNote.current.get(noteId)) || 0
  }, [noteId])

  return (
    <div className={className ? `note-editor ${className}` : 'note-editor'}>
      <div className="toolbar" role="toolbar" aria-label="排版工具栏">
        <div className="tool-group">
          <button
            type="button"
            className="tool"
            title="撤销"
            disabled={!active.canUndo}
            onClick={() => run((editor) => editor.chain().focus().undo().run())}
          >
            <Undo size={15} />
          </button>
          <button
            type="button"
            className="tool"
            title="重做"
            disabled={!active.canRedo}
            onClick={() => run((editor) => editor.chain().focus().redo().run())}
          >
            <Redo size={15} />
          </button>
        </div>

        <span className="tool-sep" aria-hidden="true" />

        <div className="tool-group">
          {/* 块级样式是**选择器**，不是一个能"按下去/弹起来"的开关：此前它写成三枚互斥的
              按钮，其中"正文"在任何普通段落里都亮着（`isActive('paragraph')` 为真），
              于是工具栏上永远挂着一枚蓝色的"选中"按钮——用户看到的是一枚说不清语义的
              模式开关（界面评审 N2）。改成下拉之后，触发器上写的就是**当前块级样式**
              （正文 / 一级标题 / 二级标题），选中态落在菜单项上，工具栏上不再有常亮的蓝底；
              顺带把三个按钮压成一个，正是 N1 要的"压到 2–3 组"。 */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button
                type="button"
                className="tool tool-style"
                title="段落样式"
                aria-label="段落样式"
              >
                <span className="tool-style-text">{blockLabel(active)}</span>
                <ChevronDown size={13} aria-hidden="true" />
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" sideOffset={4} className="min-w-[132px]">
              {BLOCK_STYLES.map((style) => (
                <DropdownMenuCheckboxItem
                  key={style.title}
                  title={style.title}
                  checked={style.isActive(active)}
                  onSelect={() => run(style.apply)}
                >
                  {style.title}
                </DropdownMenuCheckboxItem>
              ))}
            </DropdownMenuContent>
          </DropdownMenu>

          <button
            type="button"
            className={`tool${active.bold ? ' tool-on' : ''}`}
            title="粗体"
            onClick={() => run((editor) => editor.chain().focus().toggleBold().run())}
          >
            <Bold size={15} />
          </button>
          <button
            type="button"
            className={`tool${active.italic ? ' tool-on' : ''}`}
            title="斜体"
            onClick={() => run((editor) => editor.chain().focus().toggleItalic().run())}
          >
            <Italic size={15} />
          </button>
          <button
            type="button"
            className={`tool${active.underline ? ' tool-on' : ''}`}
            title="下划线"
            onClick={() => run((editor) => editor.chain().focus().toggleUnderline().run())}
          >
            <UnderlineIcon size={15} />
          </button>
          <button
            type="button"
            className={`tool${active.strike ? ' tool-on' : ''}`}
            title="删除线"
            onClick={() => run((editor) => editor.chain().focus().toggleStrike().run())}
          >
            <Strikethrough size={15} />
          </button>
          {/* 行内标记与列表**同一组**：它们都是"给这段文字排版"，中间那条竖线只会在
              7 枚按钮里再切一刀、把分组数推到 4（界面评审 N1：压到 2–3 组）。
              现在全条只有两条线：历史 ｜ 排版 ｜ 更多。 */}
          <button
            type="button"
            className={`tool${active.bullet ? ' tool-on' : ''}`}
            title="无序列表"
            onClick={() => run((editor) => editor.chain().focus().toggleBulletList().run())}
          >
            <List size={15} />
          </button>
          <button
            type="button"
            className={`tool${active.ordered ? ' tool-on' : ''}`}
            title="有序列表"
            onClick={() => run((editor) => editor.chain().focus().toggleOrderedList().run())}
          >
            <ListOrdered size={15} />
          </button>
          <button
            type="button"
            className={`tool${active.task ? ' tool-on' : ''}`}
            title="待办清单"
            onClick={() => run((editor) => editor.chain().focus().toggleTaskList().run())}
          >
            <ListTodo size={15} />
          </button>
        </div>

        <span className="tool-sep" aria-hidden="true" />

        {/* 低频的四项收进「更多」：引用 / 代码块 / 链接 / 插入图片。
            它们都是"偶尔用一次"的动作，摆在工具栏上占掉的是最常点的那几枚按钮的宽度
            （界面评审 N1）。功能一个不少，只是多一层。 */}
        <div className="tool-group">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button type="button" className="tool" title="更多" aria-label="更多">
                <Ellipsis size={15} />
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" sideOffset={4} className="min-w-[148px]">
              <DropdownMenuItem
                title="引用"
                className={active.quote ? 'tool-menu-on' : undefined}
                onSelect={() => run((editor) => editor.chain().focus().toggleBlockquote().run())}
              >
                <Quote size={15} />
                引用
              </DropdownMenuItem>
              <DropdownMenuItem
                title="代码块"
                className={active.code ? 'tool-menu-on' : undefined}
                onSelect={() => run((editor) => editor.chain().focus().toggleCodeBlock().run())}
              >
                <Code size={15} />
                代码块
              </DropdownMenuItem>
              <DropdownMenuItem
                title="链接"
                className={active.link ? 'tool-menu-on' : undefined}
                onSelect={toggleLink}
              >
                <LinkIcon size={15} />
                链接
              </DropdownMenuItem>
              <DropdownMenuItem
                title={noteId ? '插入图片' : '保存后才能插入图片'}
                disabled={uploading || !noteId}
                onSelect={pickImage}
              >
                <ImageIcon size={15} />
                {uploading ? '图片上传中…' : '插入图片'}
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        <div className="toolbar-right">
          {/* 上传中要有可见反馈：从"粘/选"到图片落进正文之间有一段时间，
              只把按钮置灰的话，用户会以为这次粘贴没被受理 */}
          {uploading ? (
            <span className="upload-hint" role="status">
              图片上传中…
            </span>
          ) : null}
          {/* 保存状态放在最左：它是"这条笔记当前的状态"，比任何动作都更该先被看到 */}
          {status}
          {/* AI 处理：星芒图标 + 三档动作下拉。放在格式工具栏与右侧动作之间——
              它属于"对内容做什么"，不属于"对这条笔记做什么"。 */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button
                type="button"
                className={`ai-trigger${aiBusy ? ' ai-busy' : ''}`}
                title={aiBusy ? 'AI 正在处理…' : 'AI 处理'}
                aria-label="AI 处理"
              >
                {aiBusy ? (
                  <span className="ai-spinner" aria-hidden="true" />
                ) : (
                  <Sparkles size={15} />
                )}
                <span className="ai-trigger-text">{aiBusy ? '处理中' : 'AI'}</span>
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" sideOffset={4} className="min-w-[200px]">
              {/* 两行式菜单项（标题 + 一句说明）：`menu-item-title` / `menu-desc`
                  是 tokens.css 里给这种菜单项准备的那一对类 */}
              <DropdownMenuItem
                className="flex-col items-start gap-0"
                disabled={aiBusy}
                onSelect={() => chooseAi('format')}
              >
                <span className="menu-item-title">智能排版</span>
                <span className="menu-desc">只调分段与标题，不改文字</span>
              </DropdownMenuItem>
              <DropdownMenuItem
                className="flex-col items-start gap-0"
                disabled={aiBusy}
                onSelect={() => chooseAi('polish')}
              >
                <span className="menu-item-title">内容润色</span>
                <span className="menu-desc">只改措辞与标点，不动结构</span>
              </DropdownMenuItem>
              <DropdownMenuItem
                className="flex-col items-start gap-0"
                disabled={aiBusy}
                onSelect={() => chooseAi('both')}
              >
                <span className="menu-item-title">排版并润色</span>
                <span className="menu-desc">两件事一起做</span>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          {actions}
        </div>

        <input
          ref={fileInputRef}
          type="file"
          accept="image/png,image/jpeg,image/gif,image/webp,image/bmp"
          className="file-input"
          aria-label="插入图片"
          onChange={(event) => void onFileChange(event)}
        />
      </div>

      <div ref={bodyRef} className={`editor-body${loading ? ' is-loading' : ''}`}>
        <div className="editor-column">
          {header}
          {/* 单实例：切换笔记由画布原地换文档并清撤销栈，这里不上 key、不重建 */}
          <NoteCanvas
            ref={canvasRef}
            value={value}
            editable={editable}
            noteId={noteId}
            uploadImage={uploadImageForEditor}
            onValueChange={onValueChange}
            onReady={onReady}
            onChange={refresh}
          />
        </div>
      </div>
    </div>
  )
}

export default NoteEditor
