// frontend/src/features/chat/ui/TraceStepRow.tsx
/**
 * 过程面板里的**一行**（旧 `components/chat/TraceStepRow.vue`）。
 *
 * 两个位置共用：正常的一行，以及"同类工具合并"那一组**展开后的每一次调用**。
 * 同一份标记复制两遍，改一处忘一处只是时间问题——而这里装着的是
 * "这一步到底做了什么"（结论 / 入参 / 返回），最不该出现两份。
 *
 * 图标由 `stepIcons.tsx` 那张表给：这一层只认 `step.icon` 那个类别键。
 */
import { ChevronDown } from 'lucide-react'
import { useMemo, useState } from 'react'

import { resultPreview, thinkingParagraphs, type TraceStep } from '@/features/chat/model/turns'
import { formatCount } from '@/lib/format'

import { LinkText } from './LinkText'
import { StepIcon } from './stepIcons'
import {
  STEP_BODY,
  STEP_DETAIL,
  STEP_EMPTY_DIM,
  STEP_LABEL,
  STEP_ROW,
  STEP_TOGGLE,
  THINK_BLOCK,
  THINK_PARAGRAPH,
  caretClass,
  RAW_BODY,
  RAW_LABEL,
  RAW_MORE,
  RAW_NOTE,
  stepIconClass,
} from './traceStyles'

/**
 * 结论那一行是**原始 JSON** 吗（v0.26）。
 *
 * 判据是结构而不是 `JSON.parse`：老快照里那条被裁到 120 字，**根本解析不了**，
 * 而它恰恰是这里要挡的东西。所以只认"以 `{` 开头、紧跟着一个 `"键":`"。
 *
 * 为什么要挡：后端在没有摘要时会**回退到结果的开头**，而 exports / remember
 * 这几个工具回的是 dict——于是过程面板里铺出的是
 * `{"artifact_id": "art_89cb…", "name": …}` 这样的原文。
 * 宁可那一行什么都不写，也不要把 JSON 当句子印出来；原始载荷没丢，
 * 点开这一步的「入参 / 返回」就是它。
 */
function detailIsRawJson(detail: string): boolean {
  return /^\s*\{\s*"[\w.]+"\s*:/.test(detail)
}

/**
 * "被拦下 / 在等确认"的那几个摘要（二：这一行**默认展开**）。
 *
 * 判据只能是这句话本身：`StepEvent` 没有"成功/失败"这一维度，
 * 拦下与跑完都是 `status: done`。所以按**执行器写死的句式**认——
 * `agent_exec._refused` / `_awaiting` 与 `tool_loop._blocked_by_mode` 的摘要
 * 都是「没有执行（…拦下）」「等待确认」，还有权限与隔离那两条
 * （「…不能执行命令」「…拒绝执行」）。老快照里的措辞（"计划档拦下"）也在词表里，
 * 因为它就躺在用户正打开的那些会话里。
 *
 * 为什么值得默认展开：用户问"它怎么没做成这件事"时，答案就在这一行下面
 * （被哪条规则拦的、等的是哪一次确认、原文是什么）。折起来等于把答案藏在一次点击后面，
 * 而"这一行说的不是成功，是拦截"恰恰是最需要一眼看见的一句。
 */
const REFUSAL_MARKS = ['没有执行', '等待确认', '拒绝执行', '不能执行命令']

export function isRefusalDetail(detail: string): boolean {
  return REFUSAL_MARKS.some((mark) => detail.includes(mark))
}

export function TraceStepRow({
  step,
  open: hostOpen,
  onToggle,
  variant = 'plain',
  streaming = false,
}: {
  step: TraceStep
  /** 原文（入参 / 返回）是否展开。由宿主持有——它才管得住"哪几行开着"。 */
  open: boolean
  onToggle: () => void
  /** `child` = 某一组展开后的一次调用：缩进一档、图标位换成小圆点。 */
  variant?: 'plain' | 'child'
  /**
   * 这一轮还在流式生成中（v0.54）。**只影响"这一步的思考"的初始开合**：
   * 干活的时候它还摊着（用户在等，看着它想什么），**答完就自动收起来**——
   * 用户原话："输出最终结果完毕后，把思考折叠起来，就显示工具调用信息就行了。
   * 当然用户也可以展开查看。"
   */
  streaming?: boolean
}) {
  /** 展开入口只在真有原文时给：没有原文却画个能点的箭头，点了什么都不变。 */
  const hasDetail = Boolean(step.args || step.result)

  /**
   * **用户的点击压过默认值**（`null` = 他还没点过）。
   *
   * 拦下的行默认展开，但**不能变成折不起来**：点一下就该收起。
   * 所以真正的取值是"他选了就听他的，否则看默认值"，而宿主那份状态照样同步
   * （`onToggle`）——两处一起更新，下一次重渲染才不会把用户刚收起的那一行弹回去。
   */
  const [userChose, setUserChose] = useState<boolean | null>(null)
  const refusal = isRefusalDetail(step.detail)
  const open = userChose ?? (hostOpen || refusal)
  const toggle = () => {
    setUserChose(!open)
    onToggle()
  }

  /**
   * 这一步自己的思考（v0.54）：**默认值跟着流式状态走**、用户点过就听他的。
   *
   * 与上面原文那两个开关**分开**：它们是两件事（"它想了什么" vs "它拿回来什么"），
   * 合成一个的话，想看一眼推理就得把 2000 字的工具原文一起铺开。
   */
  const [thinkingChose, setThinkingChose] = useState<boolean | null>(null)
  const thinking = step.thinking ?? ''
  const thinkingOpen = thinkingChose ?? streaming

  /**
   * **超长返回先只给预览**（P2-1，照 ZCode 的两级懒加载 `previewBytes/fullBytes`）。
   *
   * 后端已经把结果裁到 2000 字，但一屏里连着展开十条就是两万字的 `<pre>`——
   * 这里再切到 600 字：够判断"它拿回来的是什么"，其余由「加载全部」给。
   * 预览态**只活在这一次渲染里**（收起再打开又回到先给预览）——记忆下来的后果
   * 就是"下次点开直接铺两万字"，那正是这一刀要避免的事。
   */
  const [fullResult, setFullResult] = useState(false)
  const preview = useMemo(() => (step.result ? resultPreview(step.result) : null), [step.result])
  const shownResult = preview !== null && !fullResult ? preview : (step.result ?? '')

  const child = variant === 'child'

  return (
    <li
      className={`${STEP_ROW} ${step.empty ? STEP_EMPTY_DIM : ''} ${
        child ? 'pl-[var(--space-4)]' : ''
      }`}
      data-kind={step.kind ?? step.icon}
    >
      {child ? (
        <span
          className="relative z-[1] mt-[8px] mx-[8px] mb-0 h-[5px] w-[5px] shrink-0 rounded-[var(--radius-pill)] bg-[var(--border-strong)]"
          aria-hidden
        />
      ) : (
        <span className={stepIconClass(step.icon)}>
          <StepIcon icon={step.icon} />
        </span>
      )}

      <div className={STEP_BODY}>
        {/*
          第一行：标签/箭头 + 结论。展开的原文是它的**下一块**——两者并排时长结论
          一换行就被「入参/返回」压住，而且原文占满整列宽度之后 JSON 与网页正文都读得顺。
        */}
        <div className={child ? 'flex items-start gap-[var(--space-1)]' : 'min-w-0'}>
          {/*
            **组内的一次调用不再重复工具名**：外面那一行已经写着「联网搜索 8 次」，
            里面八行各再写一遍只是把同一个词印八次。这里直接给结果本身。
          */}
          {hasDetail && child ? (
            <button
              type="button"
              className="inline-flex shrink-0 items-center justify-center w-[18px] h-[18px] p-0 rounded-[var(--radius-control)] cursor-pointer [transition:var(--transition-ui)] hover:bg-[var(--bg-hover)]"
              aria-expanded={open}
              aria-label={`${step.label}的原文`}
              onClick={toggle}
            >
              <ChevronDown className={caretClass(open)} size={12} />
            </button>
          ) : hasDetail ? (
            <button type="button" className={STEP_TOGGLE} aria-expanded={open} onClick={toggle}>
              {step.label}
              <ChevronDown className={caretClass(open)} size={12} />
            </button>
          ) : child && step.detail ? null : (
            <p className={STEP_LABEL}>{step.label}</p>
          )}

          {step.detail && !detailIsRawJson(step.detail) ? (
            <LinkText
              className={child ? `${STEP_DETAIL} flex-1 min-w-0 !mt-0 truncate` : STEP_DETAIL}
              text={step.detail}
            />
          ) : null}
        </div>

        {/* 这一步自己的思考（v0.54）：折叠入口那一行 + 展开后的按段正文。
            位置刻意在**标签之下、入参/返回之上**——它讲的是"这次调用是怎么想出来的"，
            顺序上先有想法才有调用；而标签仍然是这一行的头一句，所以它看上去仍是一次工具调用。 */}
        {thinking.trim() ? (
          <div className="mt-[var(--space-1)]">
            <button
              type="button"
              className={STEP_TOGGLE}
              aria-expanded={thinkingOpen}
              aria-label="这一步的思考"
              onClick={() => setThinkingChose(!thinkingOpen)}
            >
              思考
              <span className="tabular text-[length:var(--text-micro-size)] text-[var(--text-quaternary)]">
                {formatCount(thinking.length)} 字
              </span>
              <ChevronDown className={caretClass(thinkingOpen)} size={12} />
            </button>
            {thinkingOpen ? (
              <div className={THINK_BLOCK} data-testid="step-thinking">
                {thinkingParagraphs(thinking).map((paragraph, index) => (
                  // 段落是同一段文本按空行切出来的，没有稳定 id；下标即位置
                  <LinkText key={index} className={THINK_PARAGRAPH} text={paragraph} />
                ))}
              </div>
            ) : null}
          </div>
        ) : null}

        {/* 入参与返回是**原始载荷**（JSON / 工具正文），走等宽 `<pre>`，里面网址同样要能点 */}
        {hasDetail && open ? (
          <div className="mt-[var(--space-1)]">
            {step.args ? (
              <>
                <p className={RAW_LABEL}>入参</p>
                <pre className={RAW_BODY}>
                  <LinkText text={step.args} />
                </pre>
              </>
            ) : null}
            {step.result ? (
              <>
                <p className={RAW_LABEL}>
                  返回
                  {/*
                    只给了预览时**如实标出来**：不标的话，用户会以为这就是工具返回的全部，
                    而截断处常在他要的那一段之前
                  */}
                  {preview !== null ? (
                    <span className={`${RAW_NOTE} tabular`}>
                      仅预览 {formatCount(preview.length)} / {formatCount(step.result.length)} 字
                    </span>
                  ) : null}
                </p>
                <pre className={RAW_BODY}>
                  <LinkText text={shownResult} />
                </pre>
                {preview !== null ? (
                  <button
                    type="button"
                    className={RAW_MORE}
                    onClick={() => setFullResult((value) => !value)}
                  >
                    {fullResult
                      ? '收起，只看预览'
                      : `加载全部（${formatCount(step.result.length)} 字）`}
                  </button>
                ) : null}
              </>
            ) : null}
          </div>
        ) : null}
      </div>
    </li>
  )
}

// frontend/src/components/chat/TraceStepRow.vue
<script setup lang="ts">
/**
 * 过程面板里的**一行**（v0.26 抽出）。
 *
 * 抽出来是因为它现在有两个位置：正常的一行，以及"同类工具合并"那一组**展开后的
 * 每一次调用**。同一份标记复制两遍，改一处忘一处只是时间问题——而这里装着的
 * 是"这一步到底做了什么"（结论 / 入参 / 返回 / 产出的文件），最不该出现两份。
 *
 * 图标由调用方给的 `iconClass` 映射决定：**这一层不 import 图标组件**，
 * 它只认 `step.icon` 那个类别键；映射表在 `ChatView`（图标都在那儿 import）。
 */
import { computed, ref } from 'vue'

import type { TraceStep } from '@/composables/useChatTurns'
import { resultPreview } from '@/composables/useChatTurns'
import IconChevronDown from '@/components/icons/IconChevronDown.vue'
import LinkText from '@/components/ui/LinkText.vue'

const props = defineProps<{
  step: TraceStep
  /** 原文（入参 / 返回）是否展开。由宿主持有——它才管得住"哪几行开着"。 */
  open: boolean
  /** `child` = 某一组展开后的一次调用：缩进一档、图标位换成小圆点。 */
  variant?: 'plain' | 'child'
  /** 类别键 → 图标组件。 */
  icons: Record<string, unknown>
}>()

const emit = defineEmits<{ (event: 'toggle'): void }>()

/** 展开入口只在真有原文时给：没有原文却画个能点的箭头，点了什么都不变。 */
const hasDetail = computed(() => Boolean(props.step.args || props.step.result))

/**
 * 结论那一行是**原始 JSON** 吗（v0.26）。
 *
 * 判据是结构而不是 `JSON.parse`：老快照里那条被裁到 120 字，**根本解析不了**，
 * 而它恰恰是这里要挡的东西。所以只认"以 `{` 开头、紧跟着一个 `"键":`"。
 *
 * 为什么要挡：`ToolOutcome.step_detail()` 在没有摘要时会**回退到结果的开头**，
 * 而 exports / remember 这几个工具回的是 dict —— 于是过程面板里铺出的是
 * `{"artifact_id": "art_89cb…", "name": …}` 这样的原文（用户报的
 * "工具调用的 UI 排版很有问题"）。后端已经给它们补了人话摘要，这一条是给
 * **v0.26 之前存下的快照**兜底，顺带也是"以后哪个工具忘了写摘要"的安全网：
 * 宁可那一行什么都不写，也不要把 JSON 当句子印出来。
 * 原始载荷没丢——点开这一步的「入参 / 返回」就是它。
 */
const detailIsRawJson = computed(() => /^\s*\{\s*"[\w.]+"\s*:/.test(props.step.detail || ''))

/**
 * **超长返回先只给预览**（P2-1，照 ZCode 的两级懒加载 `previewBytes/fullBytes`）。
 *
 * 后端已经把结果裁到 2000 字（那是给"点开看"的预算），但一屏里连着展开十条
 * 就是两万字的 `<pre>`——真要点开的那一条反而要找半天。这里再切到 600 字：
 * 够判断"它拿回来的是什么"，其余由「加载全部」给。
 *
 * 预览态**只活在这一次渲染里**（组件本地状态）：收起这一行再打开，
 * 又回到"先给预览"——不做记忆，因为记忆下来的后果是"下次点开直接铺两万字"，
 * 那正是这一刀要避免的事。
 */
const fullResult = ref(false)

/** 超长时的那一段预览；`null` = 不用预览（短结果原样显示，也不多一个按钮）。 */
const preview = computed(() => (props.step.result ? resultPreview(props.step.result) : null))

const shownResult = computed(() =>
  preview.value !== null && !fullResult.value ? preview.value : (props.step.result ?? ''),
)
</script>

<template>
  <li
    class="step"
    :class="[
      `step-kind-${step.icon}`,
      { 'step-empty': step.empty, 'step-child': variant === 'child' },
    ]"
    :data-kind="step.kind"
  >
    <span v-if="variant === 'child'" class="step-dot" aria-hidden="true" />
    <span v-else class="step-icon">
      <component :is="icons[step.icon]" :size="13" />
    </span>
    <div class="step-body">
      <!-- **第一行**：箭头/标签 + 结论。展开的原文是它的**下一块**（v0.41 之前两者并排，
           长结论一换行就被「入参/返回」压住——用户截图报的就是这个）。
           这样分还有一个好处：原文占满整列宽度，JSON 与网页正文都读得顺。 -->
      <div class="step-line">
        <!--
          **组内的一次调用不再重复工具名**（v0.26）：外面那一行已经写着「联网搜索 8 次」，
          里面八行各再写一遍「联网搜索」只是把同一个词印八次。这里直接给**结果本身**
          （detail：查的什么词、命中几条），要展开原文就点左边那个箭头。
          没有 detail 的（少数工具不给自己的人话摘要）才退回显示标签。
        -->
        <button
          v-if="hasDetail && variant === 'child'"
          type="button"
          class="step-child-toggle"
          :aria-expanded="open"
          :aria-label="`${step.label}的原文`"
          @click="emit('toggle')"
        >
          <IconChevronDown class="step-caret" :class="{ 'step-caret-open': open }" :size="12" />
        </button>

        <!--
        有原文的那一步是**可点的**（v0.25，照 Kimi）：默认只显示 `detail` 那一行结论
        （「命中 8 段」），点开才看模型传了什么参数、工具返回了什么。只给结论的话，
        用户没法判断"检索知识库"这次查的是什么词、为什么没命中。
      -->
        <button
          v-else-if="hasDetail"
          type="button"
          class="step-label step-toggle"
          :aria-expanded="open"
          @click="emit('toggle')"
        >
          {{ step.label }}
          <IconChevronDown class="step-caret" :class="{ 'step-caret-open': open }" :size="12" />
        </button>
        <p v-else-if="!(variant === 'child' && step.detail)" class="step-label">
          {{ step.label }}
        </p>
        <!-- 结论里全是网址（搜索结果的 [1] … https://…）：**渲染成可点的链接**（v0.26）。
             这些是工具的原始摘要、不是 Markdown，所以走 `LinkText` 而不是 Markdown 渲染器——
             套一层 Markdown 会把摘要里的 `*`、`_`、`|` 当成标记吃掉。 -->
        <LinkText v-if="step.detail && !detailIsRawJson" class="step-detail" :text="step.detail" />
      </div>

      <!-- 入参与返回是**原始载荷**（JSON / 工具正文），所以走等宽 `<pre>`，
           但里面的网址同样要能点（v0.26）——搜索结果的**完整地址只在这一层**，
           上面那行结论早被裁到 120 字、大多只剩半截。 -->
      <div v-if="hasDetail && open" class="step-raw">
        <template v-if="step.args">
          <p class="step-raw-label">入参</p>
          <pre class="step-raw-body"><LinkText :text="step.args" /></pre>
        </template>
        <template v-if="step.result">
          <p class="step-raw-label">
            返回
            <!-- 只给了预览时**如实标出来**（照 ZCode 的 `xx/x 字`）：不标的话，
                 用户会以为这就是工具返回的全部，而截断处常在他要的那一段之前 -->
            <span v-if="preview !== null" class="step-raw-note tabular">
              仅预览 {{ preview.length }}/{{ step.result.length }} 字
            </span>
          </p>
          <pre class="step-raw-body"><LinkText :text="shownResult" /></pre>
          <button
            v-if="preview !== null"
            type="button"
            class="step-raw-more"
            @click="fullResult = !fullResult"
          >
            {{ fullResult ? '收起，只看预览' : `加载全部（${step.result.length} 字）` }}
          </button>
        </template>
      </div>
    </div>
  </li>
</template>

<style scoped src="src/components/chat/trace-row.css"></style>

<style scoped>
/*
 * 这一行**自己的**那点样式（外壳在 `trace-row.css`，与组的表头共用一份）。
 *
 * v0.26 把整行的样式从 `ChatView` 搬进这个组件时，组那一行（还留在 ChatView
 * 的 `.step-group`）没有跟着搬——它的图标掉了圆底、标签起始线也上下错开。
 * 所以外壳那几条现在单独放一份文件，两边 `<style scoped src>` 引同一份。
 */
/* 没有新增资料的检索轮次：压暗一档。它和"找到了新东西"的那几轮价值不同，
   一样重会让人以为每一轮都有收获 */
.step-empty .step-label,
.step-empty .step-detail {
  color: var(--text-tertiary);
}

/* 第一行：图标位之外的那条线（箭头/标签 + 结论）。
   **展开的原文不是它的一部分**——原文是下面独立的一块（见 `.step-raw`）。 */
.step-line {
  min-width: 0;
}

.step-detail {
  /* `LinkText` 的根是个 `<span>`，而这里要的是**独占一行**（标签可能是 inline-flex 的按钮）。
     不给 `display: block` 的话，结论会跟在标签后面同一行上。 */
  display: block;
  margin: var(--space-pair) 0 0;
  font-size: var(--text-micro-size);
  color: var(--text-tertiary);
  overflow-wrap: anywhere;
}

/* 原文（入参 / 返回）：**限高滚动**。它动辄上千字，全铺出来会把过程面板
   变成一屏 JSON——那正是这一轮要摆脱的东西。 */
.step-raw {
  margin: var(--space-1) 0 0;
}

.step-raw-label {
  margin: var(--space-2) 0 var(--space-1);
  font-size: var(--text-micro-size);
  color: var(--text-quaternary);
}

/* "仅预览 x/y 字"与「加载全部」：同一档小字，跟在标签右边 / 正文下面 */
.step-raw-note {
  margin-left: var(--space-2);
  color: var(--text-quaternary);
}

.step-raw-more {
  margin-top: var(--space-1);
  padding: 0;
  font-size: var(--text-micro-size);
  color: var(--accent-text);
  transition: var(--transition-ui);
}

.step-raw-more:hover {
  text-decoration: underline;
}

.step-raw-body {
  margin: 0;
  padding: var(--space-2);
  max-height: 220px;
  overflow: auto;
  background: var(--bg-subtle);
  border-radius: var(--radius-control);
  font-family: var(--font-mono);
  font-size: var(--text-micro-size);
  line-height: var(--line-code);
  color: var(--text-secondary);
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
/* 分组展开后的一次调用：缩进一档、图标位换成小圆点。
   点比图标轻——它们归属上面那一行，不该各自再抢一次注意力。 */
.step-child {
  padding-left: var(--space-4);
}

/* 组内那一次的布局：箭头（可点）+ 结果。**箭头在左**，
   与上面那一行的图标位对齐——一列竖着看下来是一条线。 */
.step-child .step-line {
  display: flex;
  align-items: flex-start;
  gap: var(--space-1);
}

/* 组内那一次的结论**只占一行**（v0.41）：它是"查的什么词 + 命中几条 + 第一条的标题与网址"，
   放开了就是两三行，一屏里十几次调用会把这栏糊成一面墙（用户截图里的样子）。
   完整内容一个字不少——在展开的「返回」里。 */
.step-child .step-detail {
  flex: 1;
  min-width: 0;
  margin-top: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.step-child-toggle {
  display: inline-flex;
  flex: 0 0 auto;
  align-items: center;
  justify-content: center;
  width: 18px;
  height: 18px;
  padding: 0;
  border: none;
  border-radius: var(--radius-control);
  background: none;
  cursor: pointer;
  transition: var(--transition-ui);
}

.step-child-toggle:hover {
  background: var(--bg-hover);
}

/* 展开的原文在孩子里**占满整列**（它已经是 `.step-line` 的下一块，
   不再是同一行里的兄弟——见模板里那段注释）。 */
.step-child .step-raw {
  margin-top: var(--space-1);
}

.step-dot {
  position: relative;
  z-index: 1;
  flex: 0 0 auto;
  width: 5px;
  height: 5px;
  /* 与 `.step-icon`（21px）的中心对齐：上面那条时间轴的竖线在 left:10px 上 */
  margin: 8px 8px 0;
  border-radius: var(--radius-pill);
  background: var(--border-strong);
}
</style>
