// frontend/src/components/knowledge/ShareDialog.vue
<script setup lang="ts">
/**
 * 知识库分享弹窗（v10「私有 + 可分享」）。
 *
 * 三个刻意的取舍：
 *
 * 1. **按登录名授出，不做成员下拉**：`/users` 是控制台级端点，成员调不通——
 *    而分享恰恰是成员最常用的动作。让 owner 敲对方的登录名，是唯一既不提权、
 *    又不泄露名册全貌的方式（后端 `services/share.py` 的说明）。
 * 2. **档位在行内改**：把"只读 / 可写"做成每行一个下拉，而不是"删了再授"——
 *    调整权限不该产生一次权限真空。
 * 3. **收回不做二次确认**：它是可逆的（再授一次即可），且确认弹窗会挡住
 *    下面的列表，让"我到底给了谁"看不清。破坏性动作的确认口径见规范 §10.3。
 */
import { onMounted, ref, watch } from 'vue'

import { grantShare, listShares, revokeShare, type Share, type SharePermission } from '@/api/shares'
import AppButton from '@/components/ui/AppButton.vue'
import AppInput from '@/components/ui/AppInput.vue'
import AppModal from '@/components/ui/AppModal.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import { useToast } from '@/composables/useToast'

const open = defineModel<boolean>('open', { required: true })

const props = defineProps<{ kbId: string; kbName: string }>()

const { notifyError, notifySuccess } = useToast()

const shares = ref<Share[]>([])
const loading = ref(false)
const loadError = ref('')
const usernameDraft = ref('')
const permissionDraft = ref<SharePermission>('read')
const granting = ref(false)
const grantError = ref('')
/** 正在改档位 / 收回的 user_id：行内按钮据此显示忙碌态。 */
const busyId = ref('')

const PERMISSION_OPTIONS: { value: SharePermission; label: string }[] = [
  { value: 'read', label: '只读' },
  { value: 'write', label: '可写' },
]

async function load(): Promise<void> {
  loading.value = true
  try {
    shares.value = (await listShares(props.kbId)).items
    loadError.value = ''
  } catch (error) {
    loadError.value = error instanceof Error ? error.message : '分享列表加载失败'
  } finally {
    loading.value = false
  }
}

watch(open, (value) => {
  if (value) {
    usernameDraft.value = ''
    permissionDraft.value = 'read'
    grantError.value = ''
    void load()
  }
})

onMounted(() => {
  if (open.value) void load()
})

async function submitGrant(): Promise<void> {
  const username = usernameDraft.value.trim()
  if (!username) {
    grantError.value = '请填写对方的登录名'
    return
  }
  granting.value = true
  grantError.value = ''
  try {
    const share = await grantShare(props.kbId, username, permissionDraft.value)
    usernameDraft.value = ''
    notifySuccess(`已分享给 ${share.name}（${share.username}）`)
    await load()
  } catch (error) {
    grantError.value = error instanceof Error ? error.message : '分享失败'
  } finally {
    granting.value = false
  }
}

async function changePermission(share: Share, permission: string): Promise<void> {
  if (permission === share.permission) return
  busyId.value = share.user_id
  try {
    await grantShare(props.kbId, share.username, permission as SharePermission)
    await load()
  } catch (error) {
    notifyError(error instanceof Error ? error.message : '调整档位失败')
    await load()
  } finally {
    busyId.value = ''
  }
}

async function revoke(share: Share): Promise<void> {
  busyId.value = share.user_id
  try {
    await revokeShare(props.kbId, share.user_id)
    notifySuccess(`已收回「${share.name}」的访问`)
    await load()
  } catch (error) {
    notifyError(error instanceof Error ? error.message : '收回失败')
  } finally {
    busyId.value = ''
  }
}
</script>

<template>
  <AppModal v-model:open="open" title="分享知识库">
    <p class="share-lead">把「{{ kbName }}」分享给其他成员。对方登录后就能在列表里看到它。</p>

    <div class="grant">
      <AppInput
        v-model="usernameDraft"
        placeholder="对方的登录名"
        aria-label="对方的登录名"
        :disabled="granting"
        @keyup.enter="submitGrant"
      />
      <AppSelect
        v-model="permissionDraft"
        :options="PERMISSION_OPTIONS"
        aria-label="访问档位"
        :disabled="granting"
      />
      <AppButton variant="primary" :disabled="granting" @click="submitGrant">
        {{ granting ? '分享中…' : '分享' }}
      </AppButton>
    </div>
    <p v-if="grantError" class="share-error" role="alert">{{ grantError }}</p>
    <p class="share-note">
      只读 = 可检索、可对话；可写 = 还能上传与删除。被分享者不能把库再转授给别人。
    </p>

    <h3 class="share-title">已分享给</h3>
    <p v-if="loading" class="share-note">正在加载…</p>
    <p v-else-if="loadError" class="share-error">{{ loadError }}</p>
    <p v-else-if="shares.length === 0" class="share-note">
      还没有分享给任何人。这个库目前只有你自己（和管理员）能看到。
    </p>
    <ul v-else class="share-list">
      <li v-for="share in shares" :key="share.user_id" class="share-row">
        <span class="share-person">
          <span class="share-name">{{ share.name }}</span>
          <span class="share-username">{{ share.username }}</span>
        </span>
        <AppSelect
          :model-value="share.permission"
          :options="PERMISSION_OPTIONS"
          :disabled="busyId === share.user_id"
          :aria-label="`调整 ${share.name} 的访问档位`"
          @update:model-value="changePermission(share, $event)"
        />
        <AppButton
          variant="danger"
          size="sm"
          :disabled="busyId === share.user_id"
          @click="revoke(share)"
        >
          收回
        </AppButton>
      </li>
    </ul>
  </AppModal>
</template>

<style scoped>
.share-lead {
  margin: 0 0 var(--space-4);
  font-size: var(--text-meta-size);
  line-height: 1.7;
  color: var(--text-secondary);
}

/* 一行完成"填登录名 → 选档位 → 分享"：输入框吃掉剩余宽度 */
.grant {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.grant :deep(.field) {
  flex: 1;
  min-width: 0;
}

.share-error {
  margin: var(--space-2) 0 0;
  font-size: var(--text-micro-size);
  color: var(--status-danger);
}

.share-note {
  margin: var(--space-2) 0 0;
  font-size: var(--text-micro-size);
  line-height: 1.7;
  color: var(--text-tertiary);
}

.share-title {
  margin: var(--space-5) 0 var(--space-2);
  font-size: var(--text-section-size);
}

.share-list {
  margin: 0;
  padding: 0;
  list-style: none;
}

.share-row {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding: var(--space-2) 0;
  border-bottom: 1px solid var(--border-hairline);
}

.share-row:last-child {
  border-bottom: none;
}

/* 显示名 + 登录名两行：后者是"账号标识"，用来核对授对了人 */
.share-person {
  display: flex;
  flex: 1;
  min-width: 0;
  flex-direction: column;
  gap: var(--space-pair);
}

.share-name {
  overflow: hidden;
  font-size: var(--text-body-size);
  color: var(--text-primary);
  text-overflow: ellipsis;
  white-space: nowrap;
}

.share-username {
  font-size: var(--text-micro-size);
  color: var(--text-tertiary);
}
</style>

// frontend-react/src/features/knowledge/ShareDialog.tsx
/**
 * 知识库分享弹窗（v10「私有 + 可分享」；旧 `ShareDialog.vue` 的行为逐条对齐）。
 *
 * 三个刻意的取舍：
 * 1. **按登录名授出，不做成员下拉**：`/users` 是控制台级端点，成员调不通——
 *    而分享恰恰是成员最常用的动作。让 owner 敲对方的登录名，是唯一既不提权、
 *    又不泄露名册全貌的方式。
 * 2. **档位在行内改**：把"只读 / 可写"做成每行一个下拉，而不是"删了再授"——
 *    调整权限不该产生一次权限真空。
 * 3. **收回不做二次确认**：它是可逆的（再授一次即可），而确认弹窗会挡住
 *    下面的列表，让"我到底给了谁"看不清。
 */
import { useCallback, useEffect, useState } from 'react'

import { grantShare, listShares, revokeShare, type Share, type SharePermission } from '@/api/shares'
import { Button, Input, Modal, Select } from '@/features/knowledge/primitives'
import { messageOf, notify } from '@/features/knowledge/store'

const PERMISSION_OPTIONS: { value: SharePermission; label: string }[] = [
  { value: 'read', label: '只读' },
  { value: 'write', label: '可写' },
]

interface ShareDialogProps {
  open: boolean
  kbId: string
  kbName: string
  onClose: () => void
}

export function ShareDialog({ open, kbId, kbName, onClose }: ShareDialogProps) {
  const [shares, setShares] = useState<Share[]>([])
  const [loading, setLoading] = useState(false)
  const [loadError, setLoadError] = useState('')
  const [usernameDraft, setUsernameDraft] = useState('')
  const [permissionDraft, setPermissionDraft] = useState<SharePermission>('read')
  const [granting, setGranting] = useState(false)
  const [grantError, setGrantError] = useState('')
  /** 正在改档位 / 收回的 user_id：行内按钮据此显示忙碌态。 */
  const [busyId, setBusyId] = useState('')

  const load = useCallback(async () => {
    setLoading(true)
    try {
      setShares((await listShares(kbId)).items)
      setLoadError('')
    } catch (cause) {
      setLoadError(messageOf(cause, '分享列表加载失败'))
    } finally {
      setLoading(false)
    }
  }, [kbId])

  // 每次打开都重新拉：别人可能刚被授出或收回，缓存一份过期的名单没有意义。
  // 顺带把上一次的草稿清掉（关掉再打开看到上次没提交的名字会让人以为已经分享了）。
  useEffect(() => {
    if (!open) return
    setUsernameDraft('')
    setPermissionDraft('read')
    setGrantError('')
    void load()
  }, [open, load])

  async function submitGrant(): Promise<void> {
    const username = usernameDraft.trim()
    if (!username) {
      setGrantError('请填写对方的登录名')
      return
    }
    setGranting(true)
    setGrantError('')
    try {
      const share = await grantShare(kbId, username, permissionDraft)
      setUsernameDraft('')
      notify.success(`已分享给 ${share.name}（${share.username}）`)
      await load()
    } catch (cause) {
      setGrantError(messageOf(cause, '分享失败'))
    } finally {
      setGranting(false)
    }
  }

  async function changePermission(share: Share, permission: string): Promise<void> {
    if (permission === share.permission) return
    setBusyId(share.user_id)
    try {
      await grantShare(kbId, share.username, permission as SharePermission)
      await load()
    } catch (cause) {
      notify.error(messageOf(cause, '调整档位失败'))
      await load()
    } finally {
      setBusyId('')
    }
  }

  async function revoke(share: Share): Promise<void> {
    setBusyId(share.user_id)
    try {
      await revokeShare(kbId, share.user_id)
      notify.success(`已收回「${share.name}」的访问`)
      await load()
    } catch (cause) {
      notify.error(messageOf(cause, '收回失败'))
    } finally {
      setBusyId('')
    }
  }

  return (
    <Modal open={open} title="分享知识库" onClose={onClose}>
      <p className="kb-lead">把「{kbName}」分享给其他成员。对方登录后就能在列表里看到它。</p>

      <div className="kb-grant">
        <Input
          className="kb-grant-input"
          value={usernameDraft}
          placeholder="对方的登录名"
          aria-label="对方的登录名"
          disabled={granting}
          onChange={(event) => setUsernameDraft(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === 'Enter') void submitGrant()
          }}
        />
        <Select
          className="kb-grant-permission"
          value={permissionDraft}
          options={PERMISSION_OPTIONS}
          aria-label="访问档位"
          disabled={granting}
          onChange={(value) => setPermissionDraft(value as SharePermission)}
        />
        <Button variant="primary" disabled={granting} onClick={() => void submitGrant()}>
          {granting ? '分享中…' : '分享'}
        </Button>
      </div>
      {grantError ? (
        <p className="kb-share-error" role="alert">
          {grantError}
        </p>
      ) : null}
      <p className="text-hint">
        只读 = 可检索、可对话；可写 = 还能上传与删除。被分享者不能把库再转授给别人。
      </p>

      <h3 className="kb-share-title">已分享给</h3>
      {loading ? <p className="text-hint">正在加载…</p> : null}
      {!loading && loadError ? <p className="kb-share-error">{loadError}</p> : null}
      {!loading && !loadError && shares.length === 0 ? (
        <p className="text-hint">还没有分享给任何人。这个库目前只有你自己（和管理员）能看到。</p>
      ) : null}
      {!loading && shares.length > 0 ? (
        <ul className="kb-share-list">
          {shares.map((share) => (
            <li key={share.user_id} className="kb-share-row">
              <span className="kb-share-person">
                <span className="kb-share-name">{share.name}</span>
                <span className="kb-share-username">{share.username}</span>
              </span>
              <div style={{ width: 104 }}>
                <Select
                  value={share.permission}
                  options={PERMISSION_OPTIONS}
                  disabled={busyId === share.user_id}
                  aria-label={`调整 ${share.name} 的访问档位`}
                  onChange={(value) => void changePermission(share, value)}
                />
              </div>
              <Button
                variant="danger"
                size="sm"
                disabled={busyId === share.user_id}
                onClick={() => void revoke(share)}
              >
                收回
              </Button>
            </li>
          ))}
        </ul>
      ) : null}
    </Modal>
  )
}
