// frontend-react/src/features/misc/settings/ModelRegistryPanel.tsx
/**
 * 模型注册：供应商 → 模型清单（调研报告 G1 / v0.8 归属整理）
 * ——与旧前端 `components/settings/ModelRegistryPanel.vue` 逐条对应。
 *
 * **这里只做一件事：把模型登记进来。** 地址、凭据、模型名、维度都在这儿填。
 * "哪个用途用哪个模型"不在这儿绑——向量化的默认模型在「设置 → 向量化」里选，
 * 对话的在「设置 → 对话模型」里选。理由是**注册入口必须唯一**：
 * 同一件事（这家供应商的这把钥匙）能在两个地方写，就必然会漂。
 *
 * 模型行上仍会显示「用于向量化」这类标记，但那是**只读的状态**：
 * 让用户删模型之前知道会影响什么。
 *
 * 密钥纪律：只显示掩码。**改名字时不回传掩码**——那会把密钥写成掩码。
 */
import { useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, RefreshCw } from 'lucide-react'

import {
  createProvider,
  deleteModel,
  deleteProvider,
  getRegistry,
  listAvailableModels,
  registerModel,
  testProvider,
  updateModel,
  updateProvider,
  type AvailableModel,
  type Provider,
  type RegisteredModel,
} from '@/api/modelRegistry'

import { notifyError, notifySuccess } from '../shared/toast'
import {
  Button,
  Checkbox,
  ConfirmDialog,
  EmptyState,
  Field,
  MenuItem,
  RowMenu,
  Select,
  SkeletonBlock,
  StatusTag,
  TextInput,
} from '../shared/ui'
import { mergeModelOptions, presetModelMeta } from './providerPresets'

export const REGISTRY_QUERY_KEY = ['model-registry'] as const

interface ModelDraft {
  model_id: string
  label: string
  dim: string
  capabilities: string[]
}

const EMPTY_MODEL: ModelDraft = { model_id: '', label: '', dim: '', capabilities: [] }

type DeleteTarget =
  { kind: 'provider'; provider: Provider } | { kind: 'model'; model: RegisteredModel }

export function ModelRegistryPanel() {
  const queryClient = useQueryClient()

  const registry = useQuery({ queryKey: REGISTRY_QUERY_KEY, queryFn: getRegistry })

  const [busy, setBusy] = useState('')
  const [addingProvider, setAddingProvider] = useState(false)
  const [selectedPresetId, setSelectedPresetId] = useState('')
  const [providerDraft, setProviderDraft] = useState({
    kind: 'llm',
    name: '',
    base_url: '',
    api_key: '',
  })
  const [editingProvider, setEditingProvider] = useState('')
  const [providerEdit, setProviderEdit] = useState({ name: '', base_url: '', api_key: '' })
  const [addingModelFor, setAddingModelFor] = useState('')
  const [modelDraft, setModelDraft] = useState<ModelDraft>(EMPTY_MODEL)
  const [availableModels, setAvailableModels] = useState<AvailableModel[]>([])
  const [loadingAvailable, setLoadingAvailable] = useState(false)
  const [availableError, setAvailableError] = useState('')
  /** 候选属于哪个供应商——避免上一个供应商的列表串进下一个的表单。 */
  const availableForRef = useRef('')
  const [editingModel, setEditingModel] = useState('')
  const [modelEdit, setModelEdit] = useState<ModelDraft>(EMPTY_MODEL)
  const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null)

  const providers = registry.data?.providers ?? []
  const kinds = registry.data?.provider_kinds ?? {}
  const capabilities = registry.data?.capabilities ?? {}
  const slots = registry.data?.slots ?? []
  const presets = registry.data?.provider_presets ?? []

  const invalidate = () => queryClient.invalidateQueries({ queryKey: REGISTRY_QUERY_KEY })

  const presetOptions = [
    // 自定义 = 自己填一个地址
    { value: '', label: '自定义' },
    ...presets.map((preset) => ({ value: preset.id, label: preset.label })),
  ]
  const selectedPreset = presets.find((preset) => preset.id === selectedPresetId) ?? null

  function onPresetPick(id: string): void {
    setSelectedPresetId(id)
    const preset = presets.find((item) => item.id === id)
    if (!preset) {
      // 回到自定义：清空由预设填进来的名称与地址，避免半截状态
      setProviderDraft((current) => ({ ...current, name: '', base_url: '' }))
      return
    }
    setProviderDraft((current) => ({
      ...current,
      kind: preset.kind,
      name: preset.label,
      base_url: preset.base_url,
    }))
  }

  const kindOptions = Object.entries(kinds).map(([value, label]) => ({ value, label }))

  const modelsOf = (providerId: string): RegisteredModel[] =>
    (registry.data?.models ?? []).filter((item) => item.provider_id === providerId)

  /**
   * 用途键 → 中文名。**只用于模型行上的「用于向量化」标记**：绑定动作在
   * 「向量化 / 对话模型」面板里做，但"这个模型正被谁用着"要在这里看得见——
   * 删它之前得知道会影响什么。
   */
  const slotLabel = (key: string): string => slots.find((item) => item.slot === key)?.label ?? key

  const availableOptions = availableModels.map((item) => ({
    value: item.model_id,
    label: item.owned_by ? `${item.model_id} · ${item.owned_by}` : item.model_id,
  }))

  const createProviderMutation = useMutation({
    mutationFn: () => createProvider(providerDraft),
    onSuccess: async () => {
      setProviderDraft({ kind: 'llm', name: '', base_url: '', api_key: '' })
      setSelectedPresetId('')
      setAddingProvider(false)
      await invalidate()
      notifySuccess('供应商已添加')
    },
    onError: (cause: unknown) => notifyError(messageOf(cause, '添加失败')),
    onMutate: () => setBusy('provider:create'),
    onSettled: () => setBusy(''),
  })

  const updateProviderMutation = useMutation({
    mutationFn: (provider: Provider) =>
      updateProvider(provider.id, {
        name: providerEdit.name,
        base_url: providerEdit.base_url,
        // 只有用户真填了才带上 api_key；留空表示保持原值
        ...(providerEdit.api_key ? { api_key: providerEdit.api_key } : {}),
      }),
    onSuccess: async () => {
      setEditingProvider('')
      await invalidate()
      notifySuccess('供应商已更新')
    },
    onError: (cause: unknown) => notifyError(messageOf(cause, '更新失败')),
  })

  /** 探活供应商：登记时最会填错的就是地址与凭据。 */
  const testProviderMutation = useMutation({
    mutationFn: (provider: Provider) => testProvider(provider.id),
    onMutate: (provider) => setBusy(`test:${provider.id}`),
    onSuccess: (result) => notifySuccess(result.detail || '连接正常'),
    onError: (cause: unknown) => notifyError(messageOf(cause, '测试失败')),
    onSettled: () => setBusy(''),
  })

  const toggleProviderMutation = useMutation({
    mutationFn: (provider: Provider) => updateProvider(provider.id, { enabled: !provider.enabled }),
    onMutate: (provider) => setBusy(`provider:${provider.id}`),
    onError: (cause: unknown) => notifyError(messageOf(cause, '操作失败')),
    onSettled: async () => {
      setBusy('')
      await invalidate()
    },
  })

  const registerModelMutation = useMutation({
    mutationFn: (providerId: string) =>
      registerModel({
        provider_id: providerId,
        model_id: modelDraft.model_id.trim(),
        label: modelDraft.label,
        dim: modelDraft.dim ? Number(modelDraft.dim) : null,
        capabilities: modelDraft.capabilities,
      }),
    onSuccess: async () => {
      setAddingModelFor('')
      setAvailableModels([])
      setAvailableError('')
      await invalidate()
      notifySuccess('模型已登记')
    },
    onError: (cause: unknown) => notifyError(messageOf(cause, '登记失败')),
    onMutate: () => setBusy('model:create'),
    onSettled: () => setBusy(''),
  })

  const updateModelMutation = useMutation({
    mutationFn: (model: RegisteredModel) =>
      updateModel(model.id, {
        model_id: modelEdit.model_id,
        label: modelEdit.label,
        dim: modelEdit.dim ? Number(modelEdit.dim) : null,
        capabilities: modelEdit.capabilities,
      }),
    onSuccess: async () => {
      setEditingModel('')
      await invalidate()
      notifySuccess('模型已更新')
    },
    onError: (cause: unknown) => notifyError(messageOf(cause, '更新失败')),
  })

  const confirmDelete = useMutation({
    mutationFn: (target: DeleteTarget) =>
      target.kind === 'provider'
        ? deleteProvider(target.provider.id)
        : deleteModel(target.model.id),
    onSuccess: async (_result, target) => {
      setDeleteTarget(null)
      await invalidate()
      notifySuccess(target.kind === 'provider' ? '供应商已删除' : '模型已删除')
    },
    onError: (cause: unknown) => notifyError(messageOf(cause, '删除失败')),
  })

  /**
   * 拉取该供应商上游可用的模型，喂给「添加模型」的候选框。
   *
   * **失败不弹错误通知**：手写模型 ID 这条出路一直在，探测失败只该是一句就地提示，
   * 不该打断"我要手填"这个动作。
   */
  async function loadAvailable(provider: Provider): Promise<void> {
    availableForRef.current = provider.id
    setLoadingAvailable(true)
    setAvailableError('')
    setAvailableModels([])
    try {
      const result = await listAvailableModels(provider.id)
      if (availableForRef.current !== provider.id) return // 用户已经切走，别写回旧列表
      setAvailableModels(result.models)
    } catch (cause) {
      if (availableForRef.current !== provider.id) return
      setAvailableError(cause instanceof Error ? cause.message : '拉取失败')
    } finally {
      if (availableForRef.current === provider.id) setLoadingAvailable(false)
    }
  }

  function startAddModel(provider: Provider): void {
    setAddingModelFor(provider.id)
    setModelDraft(EMPTY_MODEL)
    void loadAvailable(provider)
  }

  /**
   * 从预设建议里选中一条模型时，把能力与维度也带上。
   *
   * **只有预设里的模型才有这待遇**：手写或上游探测到的 ID 没有元数据可填，
   * 强行猜能力等于替用户做决定（一个 embedding 模型被标成 chat，建库时才发现）。
   */
  const setModelId = (value: string): void => {
    const provider = providers.find((item) => item.id === addingModelFor)
    if (provider) {
      const match = presetModelMeta(presets, provider, value)
      if (match) {
        setModelDraft((current) => ({
          ...current,
          model_id: value,
          capabilities: [...match.capabilities],
          dim: match.dim !== null ? String(match.dim) : current.dim,
          label: current.label || match.label,
        }))
        return
      }
    }
    setModelDraft((current) => ({ ...current, model_id: value }))
  }

  /** 勾选/取消一个能力标记。 */
  const toggleCapability = (
    setter: (updater: (current: ModelDraft) => ModelDraft) => void,
    name: string,
  ) => {
    setter((current) => ({
      ...current,
      capabilities: current.capabilities.includes(name)
        ? current.capabilities.filter((item) => item !== name)
        : [...current.capabilities, name],
    }))
  }

  if (registry.isLoading) return <SkeletonBlock variant="text" rows={4} />

  if (registry.isError) {
    return <EmptyState title="读不到模型注册表" hint={messageOf(registry.error, '请稍后重试')} />
  }

  const deleteLead = !deleteTarget
    ? ''
    : deleteTarget.kind === 'provider'
      ? `删除供应商「${deleteTarget.provider.name}」？`
      : `删除模型「${deleteTarget.model.label || deleteTarget.model.model_id}」？`
  const deleteNote = !deleteTarget
    ? ''
    : deleteTarget.kind === 'provider'
      ? `它下面的 ${deleteTarget.provider.model_count} 个模型会被一并删除，引用这些模型的用途会自动解绑。`
      : deleteTarget.model.bound_slots.length > 0
        ? `它正被 ${deleteTarget.model.bound_slots.length} 个用途使用，删除后会自动解绑。`
        : ''

  return (
    <div className="m-block">
      <div className="m-block-head">
        <h3 className="m-block-title">
          供应商
          <span className="text-hint">
            一个供应商 = 一个接口地址 + 一把凭据；同一个地址下可以登记多个模型。
          </span>
        </h3>
        <Button icon={<Plus size={14} />} onClick={() => setAddingProvider((value) => !value)}>
          {addingProvider ? '取消' : '添加供应商'}
        </Button>
      </div>

      {addingProvider && (
        <div className="m-form-card">
          <div className="m-form-grid">
            {/* 预设：一键填好名称与接口地址（各家地址不一样，抄地址是纯摩擦） */}
            <div className="m-field-wide">
              <Field label="预设">
                <Select
                  value={selectedPresetId}
                  onValueChange={onPresetPick}
                  options={presetOptions}
                  label="供应商预设"
                />
              </Field>
            </div>
            {selectedPreset?.hint && <p className="m-preset-hint">{selectedPreset.hint}</p>}
            <Field label="类别">
              <Select
                value={providerDraft.kind}
                onValueChange={(kind) => setProviderDraft((current) => ({ ...current, kind }))}
                options={kindOptions}
                label="供应商类别"
              />
            </Field>
            <Field label="名称" htmlFor="provider-name">
              <TextInput
                id="provider-name"
                value={providerDraft.name}
                onValueChange={(name) => setProviderDraft((current) => ({ ...current, name }))}
                placeholder="例如：深度求索"
              />
            </Field>
            <div className="m-field-wide">
              <Field label="接口地址" htmlFor="provider-url">
                <TextInput
                  id="provider-url"
                  value={providerDraft.base_url}
                  onValueChange={(base_url) =>
                    setProviderDraft((current) => ({ ...current, base_url }))
                  }
                  placeholder="https://api.deepseek.com"
                />
              </Field>
            </div>
            <div className="m-field-wide">
              <Field label="API Key" htmlFor="provider-key">
                <TextInput
                  id="provider-key"
                  type="password"
                  value={providerDraft.api_key}
                  onValueChange={(api_key) =>
                    setProviderDraft((current) => ({ ...current, api_key }))
                  }
                  placeholder="sk-…"
                />
              </Field>
            </div>
          </div>
          <div className="m-form-actions">
            <Button
              variant="primary"
              disabled={busy === 'provider:create' || !providerDraft.name.trim()}
              onClick={() => createProviderMutation.mutate()}
            >
              {busy === 'provider:create' ? '添加中…' : '添加'}
            </Button>
          </div>
        </div>
      )}

      {providers.length === 0 && !addingProvider && (
        <p className="m-muted">还没有供应商。不添加也能用「精细」配置。</p>
      )}

      {providers.map((provider) => (
        <div key={provider.id} className="m-provider">
          {/* 卡内三段式：标题 → 元信息 → 次要操作。
              操作全部收进右上角「⋯」——五个按钮平铺会把卡片变成按钮墙 */}
          <div className="m-provider-head">
            <div className="m-provider-title">
              <span className="m-provider-name">{provider.name}</span>
              {!provider.enabled && <StatusTag tone="warning" label="已停用" />}
            </div>
            <RowMenu label={`${provider.name} 的操作`} align="right">
              <MenuItem
                disabled={!provider.api_key_configured || busy === `test:${provider.id}`}
                onSelect={() => testProviderMutation.mutate(provider)}
              >
                <RefreshCw size={14} />
                测试连接
              </MenuItem>
              <MenuItem
                onSelect={() => {
                  setEditingProvider(provider.id)
                  // **密钥栏留空**：留空 = 不改。把掩码填进去会被当成新密钥
                  setProviderEdit({
                    name: provider.name,
                    base_url: provider.base_url,
                    api_key: '',
                  })
                }}
              >
                编辑
              </MenuItem>
              <MenuItem onSelect={() => startAddModel(provider)}>添加模型</MenuItem>
              <MenuItem onSelect={() => toggleProviderMutation.mutate(provider)}>
                {provider.enabled ? '停用' : '启用'}
              </MenuItem>
              <MenuItem danger onSelect={() => setDeleteTarget({ kind: 'provider', provider })}>
                删除
              </MenuItem>
            </RowMenu>
          </div>

          <p className="m-provider-meta">
            <span>{kinds[provider.kind] ?? provider.kind}</span>
            <span className="sep">·</span>
            <span className="tabular">
              {provider.api_key_configured ? provider.api_key_hint : '未配密钥'}
            </span>
            <span className="sep">·</span>
            <span className="tabular">{provider.model_count} 个模型</span>
          </p>
          {provider.base_url && <p className="m-provider-url">{provider.base_url}</p>}

          {editingProvider === provider.id && (
            <div className="m-form-card">
              <div className="m-form-grid">
                <Field label="名称" htmlFor={`provider-edit-name-${provider.id}`}>
                  <TextInput
                    id={`provider-edit-name-${provider.id}`}
                    value={providerEdit.name}
                    onValueChange={(name) => setProviderEdit((current) => ({ ...current, name }))}
                  />
                </Field>
                <div className="m-field-wide">
                  <Field label="接口地址" htmlFor={`provider-edit-url-${provider.id}`}>
                    <TextInput
                      id={`provider-edit-url-${provider.id}`}
                      value={providerEdit.base_url}
                      onValueChange={(base_url) =>
                        setProviderEdit((current) => ({ ...current, base_url }))
                      }
                    />
                  </Field>
                </div>
                <div className="m-field-wide">
                  <Field label="API Key" htmlFor={`provider-edit-key-${provider.id}`}>
                    <TextInput
                      id={`provider-edit-key-${provider.id}`}
                      type="password"
                      value={providerEdit.api_key}
                      onValueChange={(api_key) =>
                        setProviderEdit((current) => ({ ...current, api_key }))
                      }
                      placeholder="留空表示不修改"
                    />
                  </Field>
                </div>
              </div>
              <div className="m-form-actions">
                <Button onClick={() => setEditingProvider('')}>取消</Button>
                <Button
                  variant="primary"
                  disabled={busy === `provider:${provider.id}`}
                  onClick={() => updateProviderMutation.mutate(provider)}
                >
                  保存
                </Button>
              </div>
            </div>
          )}

          {addingModelFor === provider.id && (
            <div className="m-form-card">
              <div className="m-form-grid">
                <Field label="模型 ID" htmlFor={`model-id-${provider.id}`}>
                  {/* 候选来自上游探测（**不落库**）+ 预设建议；手写这条路一直在。
                      用原生 `datalist`：可搜索、可手写、键盘可达，且没有额外的浮层要维护 */}
                  <TextInput
                    id={`model-id-${provider.id}`}
                    list={`model-options-${provider.id}`}
                    value={modelDraft.model_id}
                    onValueChange={setModelId}
                    placeholder="选择或直接输入，如 BAAI/bge-m3"
                  />
                  <datalist id={`model-options-${provider.id}`}>
                    {mergeModelOptions(availableOptions, presets, provider).map((option) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </datalist>
                </Field>
                <Field label="显示名" optional htmlFor={`model-label-${provider.id}`}>
                  <TextInput
                    id={`model-label-${provider.id}`}
                    value={modelDraft.label}
                    onValueChange={(label) => setModelDraft((current) => ({ ...current, label }))}
                    placeholder="对话主力"
                  />
                </Field>
                <Field label="向量维度" optional htmlFor={`model-dim-${provider.id}`}>
                  <TextInput
                    id={`model-dim-${provider.id}`}
                    value={modelDraft.dim}
                    onValueChange={(dim) => setModelDraft((current) => ({ ...current, dim }))}
                    placeholder="仅向量化模型需要"
                  />
                </Field>
                <div className="m-field-wide field">
                  <span className="field-label">能力</span>
                  <div className="m-cap-row">
                    {Object.entries(capabilities).map(([key, label]) => (
                      <Checkbox
                        key={key}
                        checked={modelDraft.capabilities.includes(key)}
                        onCheckedChange={() => toggleCapability(setModelDraft, key)}
                      >
                        {label}
                      </Checkbox>
                    ))}
                  </div>
                </div>
              </div>
              {/* 候选来自上游探测：说清"有没有的选"，失败/为空都指明手写这条出路 */}
              <p className="m-source-note">
                {loadingAvailable
                  ? '正在从供应商拉取候选模型…'
                  : availableError
                    ? `拉取候选失败：${availableError}。可直接输入模型 ID。`
                    : availableModels.length > 0
                      ? `已拉取到 ${availableModels.length} 个候选，可搜索选择，也可直接输入。`
                      : '供应商没有返回模型列表，手动填写模型 ID。'}
                {!loadingAvailable && (
                  <button
                    type="button"
                    className="m-source-refresh"
                    onClick={() => void loadAvailable(provider)}
                  >
                    重新拉取
                  </button>
                )}
              </p>
              <div className="m-form-actions">
                <Button onClick={() => setAddingModelFor('')}>取消</Button>
                <Button
                  variant="primary"
                  disabled={busy === 'model:create' || !modelDraft.model_id.trim()}
                  onClick={() => registerModelMutation.mutate(provider.id)}
                >
                  登记
                </Button>
              </div>
            </div>
          )}

          {modelsOf(provider.id).length > 0 ? (
            <ul className="m-model-list">
              {modelsOf(provider.id).map((model) => (
                <li key={model.id} className="m-model-row">
                  <div className="m-model-title">
                    <span className="m-model-name">{model.label || model.model_id}</span>
                    <span className="m-model-meta">
                      <span className="tabular">{model.model_id}</span>
                      {model.dim && (
                        <>
                          <span className="sep">·</span>
                          <span className="tabular">{model.dim} 维</span>
                        </>
                      )}
                      {model.capabilities.map((cap) => (
                        <span key={cap}>
                          <span className="sep">·</span>
                          <span>{capabilities[cap] ?? cap}</span>
                        </span>
                      ))}
                    </span>
                  </div>
                  {/* 正被哪些用途用着：一眼能看出"删了会影响什么" */}
                  {model.bound_slots.map((slot) => (
                    <StatusTag key={slot} tone="success" label={`用于${slotLabel(slot)}`} />
                  ))}
                  <RowMenu label={`${model.label || model.model_id} 的操作`} align="right">
                    <MenuItem
                      onSelect={() => {
                        setEditingModel(model.id)
                        setModelEdit({
                          model_id: model.model_id,
                          label: model.label,
                          dim: model.dim === null ? '' : String(model.dim),
                          capabilities: [...model.capabilities],
                        })
                      }}
                    >
                      编辑
                    </MenuItem>
                    <MenuItem danger onSelect={() => setDeleteTarget({ kind: 'model', model })}>
                      删除
                    </MenuItem>
                  </RowMenu>

                  {editingModel === model.id && (
                    <div className="m-form-card m-model-edit">
                      <div className="m-form-grid">
                        <Field label="模型 ID" htmlFor={`model-edit-id-${model.id}`}>
                          <TextInput
                            id={`model-edit-id-${model.id}`}
                            value={modelEdit.model_id}
                            onValueChange={(model_id) =>
                              setModelEdit((current) => ({ ...current, model_id }))
                            }
                          />
                        </Field>
                        <Field label="显示名" htmlFor={`model-edit-label-${model.id}`}>
                          <TextInput
                            id={`model-edit-label-${model.id}`}
                            value={modelEdit.label}
                            onValueChange={(label) =>
                              setModelEdit((current) => ({ ...current, label }))
                            }
                          />
                        </Field>
                        <Field label="向量维度" htmlFor={`model-edit-dim-${model.id}`}>
                          <TextInput
                            id={`model-edit-dim-${model.id}`}
                            value={modelEdit.dim}
                            onValueChange={(dim) =>
                              setModelEdit((current) => ({ ...current, dim }))
                            }
                          />
                        </Field>
                        <div className="m-field-wide field">
                          <span className="field-label">能力</span>
                          <div className="m-cap-row">
                            {Object.entries(capabilities).map(([key, label]) => (
                              <Checkbox
                                key={key}
                                checked={modelEdit.capabilities.includes(key)}
                                onCheckedChange={() => toggleCapability(setModelEdit, key)}
                              >
                                {label}
                              </Checkbox>
                            ))}
                          </div>
                        </div>
                      </div>
                      <div className="m-form-actions">
                        <Button onClick={() => setEditingModel('')}>取消</Button>
                        <Button
                          variant="primary"
                          disabled={busy === `model:${model.id}`}
                          onClick={() => updateModelMutation.mutate(model)}
                        >
                          保存
                        </Button>
                      </div>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          ) : (
            addingModelFor !== provider.id && <p className="m-muted">还没有登记模型。</p>
          )}
        </div>
      ))}

      {/* 删除供应商 / 删除模型：两者的后果不同，由上面两个 computed 按目标拼出来 */}
      <ConfirmDialog
        open={deleteTarget !== null}
        title="删除确认"
        lead={deleteLead}
        note={deleteNote || undefined}
        confirmLabel="删除"
        busy={confirmDelete.isPending}
        busyLabel="删除中…"
        onCancel={() => setDeleteTarget(null)}
        onConfirm={() => deleteTarget && confirmDelete.mutate(deleteTarget)}
      />
    </div>
  )
}

function messageOf(error: unknown, fallback: string): string {
  return error instanceof Error ? error.message : fallback
}

// frontend/src/components/settings/ModelRegistryPanel.vue
<script setup lang="ts">
/**
 * 模型注册：供应商 → 模型清单（调研报告 G1 / v0.8 归属整理）。
 *
 * **这里只做一件事：把模型登记进来。** 地址、凭据、模型名、维度都在这儿填。
 * "哪个用途用哪个模型"不在这儿绑——向量化的默认模型在「设置 → 向量化」里选，
 * 对话的在「设置 → 对话模型」里选。理由是**注册入口必须唯一**：
 * 同一件事（这家供应商的这把钥匙）能在两个地方写，就必然会漂。
 *
 * 模型行上仍会显示「用于向量化」这类标记，但那是**只读的状态**：
 * 让用户删模型之前知道会影响什么。
 *
 * 密钥纪律：只显示掩码。**改名字时不回传掩码**——那会把密钥写成掩码。
 */
import { computed, onMounted, ref, watch } from 'vue'

import {
  createProvider,
  deleteModel,
  deleteProvider,
  listAvailableModels,
  registerModel,
  testProvider,
  updateModel,
  updateProvider,
  type AvailableModel,
  type Provider,
  type RegisteredModel,
} from '@/api/modelRegistry'
import { providerIcon } from '@/components/icons/brands'
import IconServer from '@/components/icons/IconServer.vue'
import { mergeModelOptions, presetModelMeta } from '@/components/settings/providerPresets'
import AppButton from '@/components/ui/AppButton.vue'
import AppCombobox from '@/components/ui/AppCombobox.vue'
import AppInput from '@/components/ui/AppInput.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import ConfirmDialog from '@/components/ui/ConfirmDialog.vue'
import InfoTip from '@/components/ui/InfoTip.vue'
import RowMenu from '@/components/ui/RowMenu.vue'
import StatusTag from '@/components/ui/StatusTag.vue'
import { useToast } from '@/composables/useToast'
import { useModelRegistryStore } from '@/stores/modelRegistry'

const { notifySuccess, notifyError } = useToast()

/**
 * 注册表来自共享 store，**不在这里另存一份**。
 *
 * 原先本面板自己 `getRegistry()` 存一个 ref，于是登记完模型只刷新了自己，
 * 「设置 → 向量化」的默认模型下拉读的却是弹窗里那份旧数据——必须关掉重开才刷新
 * （用户实测 bug）。现在登记完调 `load()` 刷新的就是全站共用的那一份。
 */
const modelRegistry = useModelRegistryStore()

const registry = computed(() => modelRegistry.registry)
const loading = ref(true)
const busy = ref('')

/** 新建供应商的表单是否展开。 */
const addingProvider = ref(false)
const providerDraft = ref({ kind: 'llm', name: '', base_url: '', api_key: '' })

/** 正在编辑的供应商 id（空 = 没有在编辑）。 */
const editingProvider = ref('')
const providerEdit = ref({ name: '', base_url: '', api_key: '' })

/** 正在给哪个供应商加模型（空 = 无）。 */
const addingModelFor = ref('')
const modelDraft = ref({ model_id: '', label: '', dim: '', capabilities: [] as string[] })

/** 「添加模型」的候选：来自上游探测，**不落库**。 */
const availableModels = ref<AvailableModel[]>([])
const loadingAvailable = ref(false)
const availableError = ref('')
/** 候选属于哪个供应商——避免上一个供应商的列表串进下一个的表单。 */
const availableFor = ref('')

/** 候选下拉项：`模型 ID · 归属`（归属只是旁注，上游不一定给）。 */
const availableOptions = computed(() =>
  availableModels.value.map((item) => ({
    value: item.model_id,
    label: item.owned_by ? `${item.model_id} · ${item.owned_by}` : item.model_id,
  })),
)

/** 正在编辑的模型 id。 */
const editingModel = ref('')
const modelEdit = ref({ model_id: '', label: '', dim: '', capabilities: [] as string[] })

const providers = computed(() => registry.value?.providers ?? [])
const kinds = computed(() => registry.value?.provider_kinds ?? {})
const capabilities = computed(() => registry.value?.capabilities ?? {})
const slots = computed(() => registry.value?.slots ?? [])
const presets = computed(() => registry.value?.provider_presets ?? [])

// ------------------------------------------------------------------ 预设

/**
 * 「添加供应商」里选中的预设（空 = 自定义 / 手动填）。
 *
 * 预设只**填表单**，不落库：用户改过的地址、名称以表单里的为准。
 * 它解决的是"各家地址不一样、还分原生与兼容两个"这件事——抄地址是纯摩擦。
 */
const selectedPresetId = ref('')

const presetOptions = computed(() => [
  // 自定义 = 自己填一个地址，用通用的服务图标；品牌图标见 icons/brands
  { value: '', label: '自定义', icon: IconServer },
  ...presets.value.map((preset) => ({
    value: preset.id,
    label: preset.label,
    icon: providerIcon(preset.id),
  })),
])

const selectedPreset = computed(
  () => presets.value.find((preset) => preset.id === selectedPresetId.value) ?? null,
)

/** 选中预设后显示的一行小字（去哪拿密钥）。没有就不占位。 */
const presetHint = computed(() => selectedPreset.value?.hint ?? '')

function onPresetPick(id: string): void {
  selectedPresetId.value = id
  const preset = presets.value.find((item) => item.id === id)
  if (!preset) {
    // 回到自定义：清空由预设填进来的名称与地址，避免半截状态
    providerDraft.value = { ...providerDraft.value, name: '', base_url: '' }
    return
  }
  providerDraft.value = {
    ...providerDraft.value,
    kind: preset.kind,
    name: preset.label,
    base_url: preset.base_url,
  }
}

/** 「添加模型」的下拉候选 = 上游探测到的 + 预设建议（去重，后者带 `· 预设` 标记）。 */
function modelOptionsFor(provider: Provider): { value: string; label: string }[] {
  return mergeModelOptions(availableOptions.value, presets.value, provider)
}

/**
 * 从预设建议里选中一条模型时，把能力与维度也带上。
 *
 * **只有预设里的模型才有这待遇**：手写或上游探测到的 ID 没有元数据可填，
 * 强行猜能力等于替用户做决定（一个 embedding 模型被标成 chat，建库时才发现）。
 */
watch(
  () => modelDraft.value.model_id,
  (value) => {
    const provider = providers.value.find((item) => item.id === addingModelFor.value)
    if (!provider) return
    const match = presetModelMeta(presets.value, provider, value)
    if (!match) return
    modelDraft.value.capabilities = [...match.capabilities]
    if (match.dim !== null) modelDraft.value.dim = String(match.dim)
    if (match.label && !modelDraft.value.label) modelDraft.value.label = match.label
  },
)

/** 某个供应商下的模型。 */
function modelsOf(providerId: string): RegisteredModel[] {
  return (registry.value?.models ?? []).filter((item) => item.provider_id === providerId)
}

/**
 * 用途键 → 中文名。
 *
 * **只用于模型行上的「用于向量化」标记**：绑定动作在「向量化 / 对话模型」面板里做
 * （v0.8 归属整理：注册只有一个入口，选择在各自的分组里），但"这个模型正被谁用着"
 * 要在这里看得见——删它之前得知道会影响什么。
 */
function slotLabel(key: string): string {
  return slots.value.find((item) => item.slot === key)?.label ?? key
}

/** 供应商类别下拉（键值对由后端给出，避免前端硬编码类别名）。 */
const kindOptions = computed(() =>
  Object.entries(kinds.value).map(([value, label]) => ({ value, label })),
)

async function load(): Promise<void> {
  loading.value = true
  try {
    // store 自己吞掉异常并记进 error，这里负责把它翻成一次提示
    await modelRegistry.load()
    if (modelRegistry.error) notifyError(modelRegistry.error)
  } finally {
    loading.value = false
  }
}

onMounted(load)

/**
 * 探活供应商（第二轮评审批注 4）。
 *
 * 从"每个用途行一颗测试按钮"挪到这里：那条按钮挤在行尾被裁掉，
 * 而且"这个地址与凭据对不对"本来就是**注册供应商时**要回答的问题；
 * 用途行只该做"选哪个模型"这一件事。
 */
async function onTestProvider(provider: Provider): Promise<void> {
  busy.value = `test:${provider.id}`
  try {
    const result = await testProvider(provider.id)
    notifySuccess(result.detail)
  } catch (cause) {
    notifyError(cause instanceof Error ? cause.message : '测试失败')
  } finally {
    busy.value = ''
  }
}

// ------------------------------------------------------------------ 供应商

async function submitProvider(): Promise<void> {
  const draft = providerDraft.value
  if (!draft.name.trim()) {
    notifyError('请填供应商名称')
    return
  }
  busy.value = 'provider:create'
  try {
    await createProvider({
      kind: draft.kind,
      name: draft.name,
      base_url: draft.base_url,
      api_key: draft.api_key,
    })
    providerDraft.value = { kind: 'llm', name: '', base_url: '', api_key: '' }
    selectedPresetId.value = ''
    addingProvider.value = false
    await load()
    notifySuccess('供应商已添加')
  } catch (cause) {
    notifyError(cause instanceof Error ? cause.message : '添加失败')
  } finally {
    busy.value = ''
  }
}

function startEditProvider(provider: Provider): void {
  editingProvider.value = provider.id
  // **密钥栏留空**：留空 = 不改。把掩码填进去会被当成新密钥
  providerEdit.value = { name: provider.name, base_url: provider.base_url, api_key: '' }
}

async function submitProviderEdit(provider: Provider): Promise<void> {
  const draft = providerEdit.value
  busy.value = `provider:${provider.id}`
  try {
    await updateProvider(provider.id, {
      name: draft.name,
      base_url: draft.base_url,
      // 只有用户真填了才带上 api_key；留空表示保持原值
      ...(draft.api_key ? { api_key: draft.api_key } : {}),
    })
    editingProvider.value = ''
    await load()
    notifySuccess('供应商已更新')
  } catch (cause) {
    notifyError(cause instanceof Error ? cause.message : '更新失败')
  } finally {
    busy.value = ''
  }
}

async function onToggleProvider(provider: Provider): Promise<void> {
  busy.value = `provider:${provider.id}`
  try {
    await updateProvider(provider.id, { enabled: !provider.enabled })
    await load()
  } catch (cause) {
    notifyError(cause instanceof Error ? cause.message : '操作失败')
  } finally {
    busy.value = ''
  }
}

/** 待确认的删除目标（供应商 / 模型共用一个 ConfirmDialog，用可辨识联合区分）。 */
type DeleteTarget =
  { kind: 'provider'; provider: Provider } | { kind: 'model'; model: RegisteredModel }

const deleteTarget = ref<DeleteTarget | null>(null)
const deleteOpen = computed({
  get: () => deleteTarget.value !== null,
  set: (value: boolean) => {
    if (!value) deleteTarget.value = null
  },
})
const deleteLead = computed(() => {
  const target = deleteTarget.value
  if (!target) return ''
  return target.kind === 'provider'
    ? `删除供应商「${target.provider.name}」？`
    : `删除模型「${target.model.label || target.model.model_id}」？`
})
const deleteNote = computed(() => {
  const target = deleteTarget.value
  if (!target) return ''
  return target.kind === 'provider'
    ? `它下面的 ${target.provider.model_count} 个模型会被一并删除，引用这些模型的用途会自动解绑。`
    : target.model.bound_slots.length > 0
      ? `它正被 ${target.model.bound_slots.length} 个用途使用，删除后会自动解绑。`
      : ''
})

function requestDelete(target: DeleteTarget): void {
  deleteTarget.value = target
}

async function confirmDelete(): Promise<void> {
  const target = deleteTarget.value
  if (!target) return
  busy.value =
    target.kind === 'provider' ? `provider:${target.provider.id}` : `model:${target.model.id}`
  try {
    if (target.kind === 'provider') {
      await deleteProvider(target.provider.id)
      notifySuccess('供应商已删除')
    } else {
      await deleteModel(target.model.id)
      notifySuccess('模型已删除')
    }
    deleteTarget.value = null
    await load()
  } catch (cause) {
    notifyError(cause instanceof Error ? cause.message : '删除失败')
  } finally {
    busy.value = ''
  }
}

// ------------------------------------------------------------------ 模型

function startAddModel(provider: Provider): void {
  addingModelFor.value = provider.id
  modelDraft.value = { model_id: '', label: '', dim: '', capabilities: [] }
  void loadAvailable(provider)
}

/**
 * 拉取该供应商上游可用的模型，喂给「添加模型」的下拉框。
 *
 * **失败不弹错误通知**：手写模型 ID 这条出路一直在，探测失败只该是一句就地提示，
 * 不该打断"我要手填"这个动作。用户要求下拉可搜索、同时保留手写，就是为这种情况。
 */
async function loadAvailable(provider: Provider): Promise<void> {
  availableFor.value = provider.id
  loadingAvailable.value = true
  availableError.value = ''
  availableModels.value = []
  try {
    const result = await listAvailableModels(provider.id)
    if (availableFor.value !== provider.id) return // 用户已经切走，别写回旧列表
    availableModels.value = result.models
  } catch (cause) {
    if (availableFor.value !== provider.id) return
    availableError.value = cause instanceof Error ? cause.message : '拉取失败'
  } finally {
    if (availableFor.value === provider.id) loadingAvailable.value = false
  }
}

async function submitModel(providerId: string): Promise<void> {
  const draft = modelDraft.value
  if (!draft.model_id.trim()) {
    notifyError('请填模型 ID')
    return
  }
  busy.value = 'model:create'
  try {
    await registerModel({
      provider_id: providerId,
      model_id: draft.model_id,
      label: draft.label,
      dim: draft.dim ? Number(draft.dim) : null,
      capabilities: draft.capabilities,
    })
    addingModelFor.value = ''
    availableModels.value = []
    availableError.value = ''
    await load()
    notifySuccess('模型已登记')
  } catch (cause) {
    notifyError(cause instanceof Error ? cause.message : '登记失败')
  } finally {
    busy.value = ''
  }
}

function startEditModel(model: RegisteredModel): void {
  editingModel.value = model.id
  modelEdit.value = {
    model_id: model.model_id,
    label: model.label,
    dim: model.dim === null ? '' : String(model.dim),
    capabilities: [...model.capabilities],
  }
}

async function submitModelEdit(model: RegisteredModel): Promise<void> {
  const draft = modelEdit.value
  busy.value = `model:${model.id}`
  try {
    await updateModel(model.id, {
      model_id: draft.model_id,
      label: draft.label,
      dim: draft.dim ? Number(draft.dim) : null,
      capabilities: draft.capabilities,
    })
    editingModel.value = ''
    await load()
    notifySuccess('模型已更新')
  } catch (cause) {
    notifyError(cause instanceof Error ? cause.message : '更新失败')
  } finally {
    busy.value = ''
  }
}

/** 勾选/取消一个能力标记。 */
function toggleCapability(target: { capabilities: string[] }, name: string): void {
  target.capabilities = target.capabilities.includes(name)
    ? target.capabilities.filter((item) => item !== name)
    : [...target.capabilities, name]
}

defineExpose({ load })
</script>

<template>
  <div class="registry">
    <p v-if="loading" class="muted">正在加载模型配置…</p>

    <template v-else>
      <!-- 供应商 → 模型清单。「用哪个模型」不在这里绑定：
           向量化的默认模型在「向量化」里选，对话的在「对话模型」里选（v0.8 归属整理） -->
      <section class="block">
        <div class="block-head">
          <div>
            <h3 class="block-title">
              供应商
              <InfoTip
                text="一个供应商 = 一个接口地址 + 一把凭据；同一个地址下可以登记多个模型。"
              />
            </h3>
          </div>
          <AppButton @click="addingProvider = !addingProvider">
            {{ addingProvider ? '取消' : '添加供应商' }}
          </AppButton>
        </div>

        <div v-if="addingProvider" class="form-card">
          <div class="form-grid">
            <!-- 预设：一键填好名称与接口地址（各家地址不一样，抄地址是纯摩擦） -->
            <label class="field field-wide">
              <span class="field-label">预设</span>
              <AppSelect
                :model-value="selectedPresetId"
                :options="presetOptions"
                aria-label="供应商预设"
                @update:model-value="onPresetPick"
              />
            </label>
            <p v-if="presetHint" class="preset-hint">{{ presetHint }}</p>
            <label class="field">
              <span class="field-label">类别</span>
              <AppSelect
                v-model="providerDraft.kind"
                :options="kindOptions"
                aria-label="供应商类别"
              />
            </label>
            <label class="field">
              <span class="field-label">名称</span>
              <AppInput v-model="providerDraft.name" placeholder="例如：深度求索" />
            </label>
            <label class="field field-wide">
              <span class="field-label">接口地址</span>
              <AppInput v-model="providerDraft.base_url" placeholder="https://api.deepseek.com" />
            </label>
            <label class="field field-wide">
              <span class="field-label">API Key</span>
              <AppInput v-model="providerDraft.api_key" type="password" placeholder="sk-…" />
            </label>
          </div>
          <div class="form-actions">
            <AppButton
              variant="primary"
              :disabled="busy === 'provider:create'"
              @click="submitProvider"
            >
              {{ busy === 'provider:create' ? '添加中…' : '添加' }}
            </AppButton>
          </div>
        </div>

        <p v-if="providers.length === 0 && !addingProvider" class="muted">
          还没有供应商。不添加也能用「精细」配置。
        </p>

        <div v-for="provider in providers" :key="provider.id" class="provider-card">
          <!-- 卡内三段式（规范 §7）：标题 → 元信息 → 次要操作。
               操作全部收进右上角「⋯」——五个按钮平铺会把卡片变成按钮墙。 -->
          <div class="provider-head">
            <div class="provider-title">
              <span class="provider-name">{{ provider.name }}</span>
              <StatusTag v-if="!provider.enabled" tone="warning" label="已停用" />
            </div>
            <RowMenu :label="`${provider.name} 的操作`">
              <template #default="{ close }">
                <!-- 探活放在供应商这一层（评审批注 4）：登记时最会填错的就是地址与凭据 -->
                <button
                  type="button"
                  :disabled="!provider.api_key_configured || busy === `test:${provider.id}`"
                  @click="(onTestProvider(provider), close())"
                >
                  测试连接
                </button>
                <button type="button" @click="(startEditProvider(provider), close())">编辑</button>
                <button type="button" @click="(startAddModel(provider), close())">添加模型</button>
                <button type="button" @click="(onToggleProvider(provider), close())">
                  {{ provider.enabled ? '停用' : '启用' }}
                </button>
                <button
                  class="menu-item-danger"
                  type="button"
                  @click="(requestDelete({ kind: 'provider', provider }), close())"
                >
                  删除
                </button>
              </template>
            </RowMenu>
          </div>

          <p class="provider-meta">
            <span>{{ kinds[provider.kind] ?? provider.kind }}</span>
            <span class="sep">·</span>
            <span class="tabular">{{
              provider.api_key_configured ? provider.api_key_hint : '未配密钥'
            }}</span>
            <span class="sep">·</span>
            <span class="tabular">{{ provider.model_count }} 个模型</span>
          </p>
          <p v-if="provider.base_url" class="provider-url">{{ provider.base_url }}</p>

          <!-- 编辑供应商 -->
          <div v-if="editingProvider === provider.id" class="form-card">
            <div class="form-grid">
              <label class="field">
                <span class="field-label">名称</span>
                <AppInput v-model="providerEdit.name" />
              </label>
              <label class="field field-wide">
                <span class="field-label">接口地址</span>
                <AppInput v-model="providerEdit.base_url" />
              </label>
              <label class="field field-wide">
                <span class="field-label">API Key</span>
                <AppInput
                  v-model="providerEdit.api_key"
                  type="password"
                  placeholder="留空表示不修改"
                />
              </label>
            </div>
            <div class="form-actions">
              <AppButton @click="editingProvider = ''">取消</AppButton>
              <AppButton
                variant="primary"
                :disabled="busy === `provider:${provider.id}`"
                @click="submitProviderEdit(provider)"
              >
                保存
              </AppButton>
            </div>
          </div>

          <!-- 加模型 -->
          <div v-if="addingModelFor === provider.id" class="form-card">
            <div class="form-grid">
              <label class="field">
                <span class="field-label">模型 ID</span>
                <AppCombobox
                  v-model="modelDraft.model_id"
                  :options="modelOptionsFor(provider)"
                  :loading="loadingAvailable"
                  :aria-label="`${provider.name} 的模型 ID`"
                  placeholder="选择或直接输入，如 BAAI/bge-m3"
                  empty-text="没探测到候选，可直接输入模型 ID"
                />
              </label>
              <label class="field">
                <span class="field-label">显示名（可选）</span>
                <AppInput v-model="modelDraft.label" placeholder="对话主力" />
              </label>
              <label class="field">
                <span class="field-label">向量维度</span>
                <AppInput v-model="modelDraft.dim" placeholder="仅向量化模型需要" />
              </label>
              <div class="field field-wide">
                <span class="field-label">能力</span>
                <div class="cap-row">
                  <label v-for="(label, key) in capabilities" :key="key" class="cap-item">
                    <input
                      type="checkbox"
                      :checked="modelDraft.capabilities.includes(key)"
                      @change="toggleCapability(modelDraft, key)"
                    />
                    {{ label }}
                  </label>
                </div>
              </div>
            </div>
            <!-- 候选来自上游探测：说清"有没有的选"，失败/为空都指明手写这条出路 -->
            <p class="source-note">
              <template v-if="loadingAvailable">正在从供应商拉取候选模型…</template>
              <template v-else-if="availableError">
                拉取候选失败：{{ availableError }}。可直接输入模型 ID。
              </template>
              <template v-else-if="availableModels.length">
                已拉取到 {{ availableModels.length }} 个候选，可搜索选择，也可直接输入。
              </template>
              <template v-else>该供应商没有返回模型列表，请直接输入模型 ID。</template>
              <button
                v-if="!loadingAvailable"
                type="button"
                class="source-refresh"
                @click="loadAvailable(provider)"
              >
                重新拉取
              </button>
            </p>
            <div class="form-actions">
              <AppButton @click="addingModelFor = ''">取消</AppButton>
              <AppButton
                variant="primary"
                :disabled="busy === 'model:create'"
                @click="submitModel(provider.id)"
              >
                登记
              </AppButton>
            </div>
          </div>

          <!-- 模型清单 -->
          <ul v-if="modelsOf(provider.id).length" class="model-list">
            <li v-for="model in modelsOf(provider.id)" :key="model.id" class="model-row">
              <div class="model-title">
                <span class="model-name">{{ model.label || model.model_id }}</span>
                <span class="model-meta">
                  <span class="tabular">{{ model.model_id }}</span>
                  <template v-if="model.dim"
                    ><span class="sep">·</span
                    ><span class="tabular">{{ model.dim }} 维</span></template
                  >
                  <template v-for="cap in model.capabilities" :key="cap"
                    ><span class="sep">·</span><span>{{ capabilities[cap] ?? cap }}</span></template
                  >
                </span>
              </div>
              <!-- 正被哪些用途用着：一眼能看出"删了会影响什么" -->
              <StatusTag
                v-for="slot in model.bound_slots"
                :key="slot"
                tone="success"
                :label="`用于${slotLabel(slot)}`"
              />
              <RowMenu class="model-menu" :label="`${model.label || model.model_id} 的操作`">
                <template #default="{ close }">
                  <button type="button" @click="(startEditModel(model), close())">编辑</button>
                  <button
                    class="menu-item-danger"
                    type="button"
                    @click="(requestDelete({ kind: 'model', model }), close())"
                  >
                    删除
                  </button>
                </template>
              </RowMenu>

              <div v-if="editingModel === model.id" class="form-card model-edit">
                <div class="form-grid">
                  <label class="field">
                    <span class="field-label">模型 ID</span>
                    <AppInput v-model="modelEdit.model_id" />
                  </label>
                  <label class="field">
                    <span class="field-label">显示名</span>
                    <AppInput v-model="modelEdit.label" />
                  </label>
                  <label class="field">
                    <span class="field-label">向量维度</span>
                    <AppInput v-model="modelEdit.dim" />
                  </label>
                  <div class="field field-wide">
                    <span class="field-label">能力</span>
                    <div class="cap-row">
                      <label v-for="(label, key) in capabilities" :key="key" class="cap-item">
                        <input
                          type="checkbox"
                          :checked="modelEdit.capabilities.includes(key)"
                          @change="toggleCapability(modelEdit, key)"
                        />
                        {{ label }}
                      </label>
                    </div>
                  </div>
                </div>
                <div class="form-actions">
                  <AppButton @click="editingModel = ''">取消</AppButton>
                  <AppButton
                    variant="primary"
                    :disabled="busy === `model:${model.id}`"
                    @click="submitModelEdit(model)"
                  >
                    保存
                  </AppButton>
                </div>
              </div>
            </li>
          </ul>
          <p v-else-if="addingModelFor !== provider.id" class="muted model-empty">
            还没有登记模型。
          </p>
        </div>
      </section>
    </template>
  </div>

  <!-- 删除供应商 / 删除模型：两者的后果不同，由 computed 按目标拼出来 -->
  <ConfirmDialog
    v-model:open="deleteOpen"
    title="删除确认"
    :lead="deleteLead"
    :note="deleteNote || undefined"
    :busy="busy.startsWith('provider:') || busy.startsWith('model:')"
    busy-label="删除中…"
    @confirm="confirmDelete"
  />
</template>

<style scoped>
.block + .block {
  margin-top: var(--space-6);
  padding-top: var(--space-5);
  border-top: 1px solid var(--border-hairline);
}

.block-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--space-3);
}

.block-title {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  margin: 0;
  font-size: var(--text-section-size);
}

/* ---- 供应商 ---- */

.provider-card {
  margin-top: var(--space-3);
  padding: var(--space-3) var(--space-4);
  background: var(--bg-subtle);
  border: 1px solid var(--border-hairline);
  border-radius: var(--radius-panel);
}

.provider-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-2);
}

.provider-title {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  min-width: 0;
}

.provider-name {
  font-size: var(--text-meta-size);
  font-weight: 500;
  color: var(--text-primary);
}

/* 元信息压成一行低对比小字：类别 · 凭据 · 模型数。
   三段挤在标题行会跟「⋯」抢位置，也会让卡片第一眼没有主次。 */
.provider-meta {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: var(--space-1);
  margin: var(--space-1) 0 0;
  font-size: var(--text-micro-size);
  color: var(--text-tertiary);
}

.provider-url {
  margin: var(--space-1) 0 0;
  font-size: var(--text-micro-size);
  color: var(--text-tertiary);
  overflow-wrap: anywhere;
}

/* ---- 模型 ---- */

.model-list {
  margin: var(--space-2) 0 0;
  padding: 0;
  list-style: none;
}

.model-row {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  flex-wrap: wrap;
  padding: var(--space-2) 0;
  border-top: 1px solid var(--border-hairline);
}

.model-title {
  display: flex;
  align-items: baseline;
  gap: var(--space-2);
  min-width: 0;
}

.model-name {
  font-size: var(--text-meta-size);
  color: var(--text-primary);
}

/* 模型 ID / 维度 / 能力合并成标题下的一行小字，
   而不是三个并列的标签——标签一多，表格就散了 */
.model-meta {
  display: flex;
  align-items: baseline;
  gap: var(--space-1);
  font-size: var(--text-micro-size);
  color: var(--text-tertiary);
}

.model-menu {
  margin-left: auto;
}

.model-edit {
  flex: 0 0 100%;
}

.model-empty {
  margin: var(--space-2) 0 0;
}

/* ---- 表单 ---- */

.form-card {
  margin-top: var(--space-3);
  padding: var(--space-3);
  background: var(--bg-canvas);
  border: 1px solid var(--border-hairline);
  border-radius: var(--radius-control);
}

.form-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: var(--space-3);
}

/* 成组容器用全局 .field；这里只补本面板特有的跨列 */
.field-wide {
  grid-column: 1 / -1;
}

/* 预设说明：与字段同宽、贴着表单，不抢视觉重量 */
.preset-hint {
  grid-column: 1 / -1;
  margin: calc(-1 * var(--space-2)) 0 0;
  font-size: var(--text-micro-size);
  line-height: 1.6;
  color: var(--text-tertiary);
}

.cap-row {
  display: flex;
  gap: var(--space-4);
  padding-top: var(--space-1);
}

.cap-item {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  font-size: var(--text-meta-size);
  color: var(--text-secondary);
}

.form-actions {
  display: flex;
  justify-content: flex-end;
  gap: var(--space-2);
  margin-top: var(--space-3);
}

.muted {
  font-size: var(--text-meta-size);
  color: var(--text-tertiary);
}

/* 候选来源说明：一行小字 + 一颗纯文字「重新拉取」 */
.source-note {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  margin: var(--space-3) 0 0;
  font-size: var(--text-micro-size);
  color: var(--text-tertiary);
}

.source-refresh {
  font-size: var(--text-micro-size);
  color: var(--accent);
}

.source-refresh:hover {
  text-decoration: underline;
}
</style>
